//! The shared link-battle RNG stream (`LinkRng`).
//!
//! In a Gen-1 link battle both Game Boys must resolve the battle identically
//! (damage variance, crits, status procs, multi-hit counts, speed-tie flips,
//! …). The original achieves this with a single shared byte stream: the host
//! (the Game Boy clocking the cable) generates a list of random bytes before
//! the battle, both sides exchange their lists, and *both* sides then consume
//! the HOST's list (the guest discards its own).
//!
//! ASM evidence (pret/pokered):
//! - `CableClub_DoBattleOrTrade` (engine/link/cable_club.asm:98-171):
//!   each side generates 10 random bytes, both lists are exchanged
//!   (`Serial_ExchangeBytes`), then:
//!   ```asm
//!   ; the list generated by the gameboy clocking the connection
//!   ; is used by both gameboys
//!   cp USING_INTERNAL_CLOCK
//!   jr z, .skipCopyingRandomNumberList
//!   ```
//!   i.e. the host keeps its own list; the guest copies the list it
//!   received (the host's).
//! - `BattleRandom` (engine/battle/core.asm:6543-6601): in
//!   `LINK_STATE_BATTLING` the normal `Random` is bypassed and the next byte
//!   of `wLinkBattleRandomNumberList` is consumed:
//!   ```asm
//!   ld a, [wLinkBattleRandomNumberListIndex]
//!   ld c, a
//!   ld b, 0
//!   ld hl, wLinkBattleRandomNumberList
//!   add hl, bc
//!   inc a
//!   ld [wLinkBattleRandomNumberListIndex], a
//!   cp SERIAL_RNS_LENGTH - 1      ; SERIAL_RNS_LENGTH = 10
//!   ld a, [hl]
//!   ...
//!   ret c                          ; index+1 < 9 → return
//!   ; if we picked the last seed, we need to recalculate the nine seeds
//!   xor a
//!   ld [wLinkBattleRandomNumberListIndex], a
//!   ld hl, wLinkBattleRandomNumberList
//!   ld b, SERIAL_RNS_LENGTH - 1
//!   .loop
//!   ld a, [hl]                     ; x*5+1 for entries 0..=8
//!   ld c, a
//!   add a
//!   add a
//!   add c
//!   inc a
//!   ld [hli], a
//!   dec b
//!   jr nz, .loop
//!   ```
//!   Reading this byte-for-byte (Z80 `cp` sets carry iff a < operand):
//!   - picks 1..=8 read `list[0]..list[7]` and return immediately;
//!   - the 9th pick reads `list[8]` and THEN refills entries `0..=8` with
//!     `(x*5+1) mod 256`, resetting the index to 0;
//!   - `list[9]` is never consumed (the wram comment literally says
//!     "shared list of 9 random numbers", wram.asm:1697 — `ds 10`).
//!   The refill is a *local* computation — there is no wire refill protocol;
//!   both sides regenerate the same values from the same list.
//!
//! [`LinkRng`] reproduces this exactly, quirk included. The list itself is
//! exchanged once per battle inside `PartyExchangeData.random_numbers` (see
//! `crate::link::link_battle_driver`), so both sides feed the constructor the
//! host's list.

use dotzuki_engine::battle::rng::BattleRng;

/// Length of the exchanged random-number list (SERIAL_RNS_LENGTH, 10).
pub const LINK_RANDOM_LIST_SIZE: usize = 10;

/// Number of bytes actually consumed per cycle (`SERIAL_RNS_LENGTH - 1`):
/// the original's off-by-one means entry 9 of the list is never read.
const LINK_RANDOM_LIST_CYCLE: usize = LINK_RANDOM_LIST_SIZE - 1;

/// The shared link-battle random stream: the host's 10-byte list, consumed
/// exactly like the original `BattleRandom` in `LINK_STATE_BATTLING`.
///
/// Implements [`BattleRng`], so the stack battle engine can draw damage /
/// crit / status / multi-hit rolls from the same stream on both sides.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LinkRng {
    list: [u8; LINK_RANDOM_LIST_SIZE],
    index: usize,
    /// Total bytes consumed (cycles * 9 + position); test-only observability.
    consumed: u64,
}

impl LinkRng {
    /// Create a stream over the host's list. The index starts at 0 (WRAM is
    /// zeroed at boot; `wLinkBattleRandomNumberListIndex` is never explicitly
    /// initialized elsewhere — engine/battle/core.asm:6552 is its only reader
    /// and 6558/6579 its only writers).
    pub fn new(list: [u8; LINK_RANDOM_LIST_SIZE]) -> Self {
        Self {
            list,
            index: 0,
            consumed: 0,
        }
    }

    /// The next byte of the shared stream — the exact `BattleRandom` link
    /// path: read `list[index]`, advance, and on the 9th pick of a cycle
    /// refill entries `0..=8` with `(x*5+1) mod 256` and reset the index.
    /// Entry 9 is never read (reproduced faithfully).
    pub fn next_stream_byte(&mut self) -> u8 {
        let value = self.list[self.index];
        self.index += 1;
        self.consumed += 1;
        if self.index >= LINK_RANDOM_LIST_CYCLE {
            // cp SERIAL_RNS_LENGTH - 1 failed (carry clear) → refill the 9 seeds.
            self.index = 0;
            for slot in self.list.iter_mut().take(LINK_RANDOM_LIST_CYCLE) {
                *slot = slot.wrapping_mul(5).wrapping_add(1);
            }
        }
        value
    }

    /// The underlying list (mostly for tests / diagnostics).
    pub fn list(&self) -> [u8; LINK_RANDOM_LIST_SIZE] {
        self.list
    }

    /// Current index into the list (0..=8 after any refill).
    pub fn index(&self) -> usize {
        self.index
    }

    /// Total number of stream bytes consumed so far.
    pub fn consumed(&self) -> u64 {
        self.consumed
    }
}

impl BattleRng for LinkRng {
    fn next_u8(&mut self) -> u8 {
        self.next_stream_byte()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact reference stream for the list `[1,2,3,4,5,6,7,8,9,10]`,
    /// derived by hand from the asm: picks 1-9 return 1..=9 (entry 9 = 10 is
    /// never read), then entries 0..=8 become `x*5+1 mod 256`:
    /// 6,11,16,21,26,31,36,41,46 — and the cycle repeats.
    fn reference_stream(initial: [u8; 10]) -> Vec<u8> {
        let mut list = initial;
        let mut out = Vec::new();
        for _cycle in 0..3 {
            for i in 0..LINK_RANDOM_LIST_CYCLE {
                out.push(list[i]);
            }
            for slot in list.iter_mut().take(LINK_RANDOM_LIST_CYCLE) {
                *slot = slot.wrapping_mul(5).wrapping_add(1);
            }
        }
        out
    }

    #[test]
    fn stream_matches_asm_reference() {
        let list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let mut rng = LinkRng::new(list);
        let got: Vec<u8> = (0..27).map(|_| rng.next_stream_byte()).collect();
        assert_eq!(got, reference_stream(list));
        // The 10th list entry is never consumed.
        assert_eq!(rng.consumed(), 27);
        assert_eq!(rng.index(), 0); // back at the start of a fresh cycle
        // Refill arithmetic over 3 cycles: after cycle 1 entries 0..=8 are
        // x*5+1 (6..=46), after cycle 2 31,56,81,106,131,156,181,206,231,
        // after cycle 3 (mod 256): 156, 26, 151, 21, 146, 16, 141, 11, 132.
        assert_eq!(rng.list()[0], 156);
        assert_eq!(rng.list()[8], 132);
        assert_eq!(rng.list()[9], 10, "entry 9 keeps its initial value forever");
    }

    #[test]
    fn refill_wraps_mod_256() {
        let mut rng = LinkRng::new([0xFF; 10]);
        // 0xFF*5+1 = 0x4FC → 0xFC (wrapping_mul/add).
        for _ in 0..LINK_RANDOM_LIST_CYCLE {
            rng.next_stream_byte();
        }
        assert_eq!(rng.list()[0], 0xFC);
    }

    #[test]
    fn battle_rng_trait_feeds_chance() {
        let list = [128, 64, 32, 16, 8, 4, 2, 1, 255, 0];
        let mut rng = LinkRng::new(list);
        use dotzuki_engine::battle::rng::BattleRng as _;
        // chance(num, den) = next_u8() % den < num.
        assert_eq!(rng.next_u8(), 128);
        assert_eq!(rng.range(200), 64 % 200);
    }

    #[test]
    fn two_instances_over_same_list_stay_locked() {
        let list = [11, 22, 33, 44, 55, 66, 77, 88, 99, 100];
        let mut a = LinkRng::new(list);
        let mut b = LinkRng::new(list);
        for _ in 0..64 {
            assert_eq!(a.next_stream_byte(), b.next_stream_byte());
        }
        assert_eq!(a.list(), b.list());
        assert_eq!(a.index(), b.index());
    }
}
