[package]
name = "pokered-tui"
version.workspace = true
edition.workspace = true

[features]
embedded-scripts = ["pokered-core/embedded-scripts"]
embedded-map-data = ["pokered-core/embedded-map-data"]

[dependencies]
pokered-core = { path = "../pokered-core" }
pokered-data = { path = "../pokered-data" }
dotzuki-engine = { git = "ssh://git@github.com/liuyanghejerry/dotzuki.git", tag = "v0.2.0" }
pokered-renderer = { path = "../pokered-renderer" }
dotzuki-renderer = { git = "ssh://git@github.com/liuyanghejerry/dotzuki.git", tag = "v0.2.0" }
dotzuki-tui = { git = "ssh://git@github.com/liuyanghejerry/dotzuki.git", tag = "v0.2.0" }
pokered-audio = { path = "../pokered-audio" }
pokered-ui = { path = "../pokered-ui" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = "0.4"
ratatui = "0.29"
crossterm = "0.28"
cpal = "0.15"
clap = { version = "4", features = ["derive"] }
