g.tap('a',8);g.cutscene();g.step(180);g.cutscene()
assert g.st()['map_name']=='ViridianCity',g.st()
g.tap('start',8);g.tap('a',8)
for _ in range(4):g.tap('down',8)
g.tap('a',8);g.tap('down',8);g.tap('down',8);g.tap('a',8)
for _ in range(4):g.tap('up',8)
g.tap('a',8);g.tap('b',8);g.tap('b',8);g.cutscene()
assert g.st()['party'][0]['species']=='Zapdos',g.st()
checkpoint('m93-league-supplied')
raise SystemExit()
