// ───────────────────────────────────────────────────────────────────────────
// direction.ts — 8-direction character sprite support (port of direction.go).
//
// 5 directions (south/north/east/south-east/north-east) are AI-generated; the
// other 3 (west/south-west/north-west) are produced by horizontal mirroring.
// ───────────────────────────────────────────────────────────────────────────

export interface DirectionInfo {
  key: string // "south", "north-east", …
  label: string // display name
  short: string // grid abbreviation (S, NE, …)
  mirrorOf: string // mirror source direction ('' → AI-generated)
  row: number // 3×3 grid row (0–2)
  col: number // 3×3 grid col (0–2)
}

/** All 8 directions, in 3×3 grid order. */
export const Directions: DirectionInfo[] = [
  { key: 'north-west', label: '¾ Back-Left', short: 'NW', mirrorOf: 'north-east', row: 0, col: 0 },
  { key: 'north', label: 'Back', short: 'N', mirrorOf: '', row: 0, col: 1 },
  { key: 'north-east', label: '¾ Back-Right', short: 'NE', mirrorOf: '', row: 0, col: 2 },
  { key: 'west', label: 'Left', short: 'W', mirrorOf: 'east', row: 1, col: 0 },
  { key: 'east', label: 'Right', short: 'E', mirrorOf: '', row: 1, col: 2 },
  { key: 'south-west', label: '¾ Front-Left', short: 'SW', mirrorOf: 'south-east', row: 2, col: 0 },
  { key: 'south', label: 'Front', short: 'S', mirrorOf: '', row: 2, col: 1 },
  { key: 'south-east', label: '¾ Front-Right', short: 'SE', mirrorOf: '', row: 2, col: 2 },
]

/** Directions generated by AI, in order (south = front reference, so it's first). */
export const GeneratedDirections = ['south', 'east', 'north', 'south-east', 'north-east']

export function listDirections(): DirectionInfo[] {
  return Directions
}

export function directionByKey(key: string): DirectionInfo | undefined {
  return Directions.find((d) => d.key === key)
}

/** isBackFacing — a back-facing direction (face hidden) where base-identity check false-positives. */
export function isBackFacing(key: string): boolean {
  return key === 'north' || key === 'north-east' || key === 'north-west'
}

interface FacingDesc {
  view: string
  camera: string
  body: string
  visibility: string
}

const facingDescs: Record<string, FacingDesc> = {
  south: {
    view: 'front view',
    camera: 'camera directly in front, at eye level',
    body: 'the character faces the viewer directly',
    visibility: 'full face visible (eyes and mouth, minimal nose detail); both arms and both legs fully visible, symmetric',
  },
  north: {
    view: 'back view',
    camera: 'camera positioned directly behind the character',
    body: 'the character faces away from the viewer',
    visibility: 'face completely hidden, only the back of the head and hair visible; back of the outfit, both arms and legs seen from behind',
  },
  east: {
    view: 'right-side profile view',
    camera: "camera at the character's right side, perpendicular to the body; strictly 2D profile, no perspective rotation",
    body: 'the character faces and moves toward the RIGHT edge of the canvas',
    visibility: 'right profile of the face only (one eye, one ear); right arm and right leg prominent, left limbs fully hidden behind the body; never show parts of the left side',
  },
  'south-east': {
    view: 'three-quarter front-right view',
    camera: 'camera at front-right, rotated about 45 degrees from straight ahead',
    body: 'the character is turned about 45 degrees to the right, mostly facing the viewer',
    visibility: '3/4 face with both eyes visible, right side emphasized; right arm and leg fully visible, left side partially visible',
  },
  'north-east': {
    view: 'three-quarter back-right view',
    camera: 'camera behind and to the right, rotated about 45 degrees',
    body: 'the character is turned away from the viewer, showing the back-right side',
    visibility: 'face hidden except a hint of the right jaw; back and right shoulder prominent, right arm and leg visible from behind',
  },
}

/** facingPromptSection — direction-lock instruction inserted into the strip prompt ('' if unknown). */
export function facingPromptSection(key: string): string {
  const d = facingDescs[key]
  if (!d) return ''
  return 'Facing direction lock (overrides any other facing or view instruction in this prompt):\n' +
    `- Required view: ${d.view} — ${d.camera}.\n` +
    `- Body orientation: ${d.body}.\n` +
    `- Visibility: ${d.visibility}.\n` +
    '- The attached reference image shows this character from the front; redraw the IDENTICAL character (same hair, outfit, colors, proportions) rotated to this view.\n' +
    '- Every frame in the strip must use this exact same viewing angle. Never drift back toward a front view and never mirror the character between frames.\n'
}
