// pokered-renderer: Graphics rendering layer for Pokémon Red/Blue Rust rewrite
//
// This is NOT a Game Boy hardware emulator. It provides a higher-level
// rendering API that draws into a 160×144 pixel framebuffer and displays
// it via a scaled window using the `pixels` crate.
//
// Most modules are re-exported from the generic `dotzuki-renderer` crate.
// Pokemon-specific modules are defined here.

// Dual-target crate: hosted builds (macOS/…) keep full std via the extern
// crate below; bare-metal GBA builds (thumbv4t-none-eabi, target_os = "none")
// compile against core + alloc only (framebuffer feature, no gpu windowing).
#![no_std]

// `#[macro_use]` so hosted builds also get std's macro surface — with plain
// `extern crate std` those macro names don't resolve.
#[cfg(not(target_os = "none"))]
#[macro_use]
extern crate std;
extern crate alloc;

// Re-export everything from dotzuki-renderer (all generic rendering modules)
pub use dotzuki_renderer::*;

use dotzuki_renderer::palette::GbColor;

// Pokemon-specific framebuffer: the indexed 4-shade buffer with an RGBA
// facade. All pokered draw code keeps calling set_pixel(Rgba)/fill_rect/
// clear on `FrameBuffer`; writes quantize through the grayscale base
// palette (exact for the pokered render chain), and the 160×144 storage
// is 5,760 bytes of packed 2bpp instead of 92,160 bytes of RGBA.
// The engine's RGBA `dotzuki_renderer::FrameBuffer` stays available for the
// true-color paths (e.g. the `--demo` tileset demo).
#[cfg(not(all(target_os = "none", target_arch = "arm")))]
pub type FrameBuffer = dotzuki_renderer::RgbaIndexedFrameBuffer<GbColor>;
// The application chooses its hardware staging format explicitly. The generic
// engine types keep the same storage and APIs on every target.
#[cfg(all(target_os = "none", target_arch = "arm"))]
pub type FrameBuffer = dotzuki_renderer::LinearRgbaIndexedFrameBuffer<GbColor>;

// Compatibility import backed by the shared platform contract.
pub(crate) mod sync_compat;

// With `#![no_std]` the Vec/String/Box/vec!/format! family leaves the prelude
// on BOTH targets. Modules glob-import this to keep using them unqualified.
#[allow(unused_imports)]
pub(crate) mod alloc_prelude {
    pub use alloc::borrow::{Cow, ToOwned};
    pub use alloc::boxed::Box;
    pub use alloc::collections::{BTreeMap, BTreeSet, VecDeque};
    pub use alloc::format;
    pub use alloc::rc::Rc;
    pub use alloc::string::{String, ToString};
    pub use alloc::vec;
    pub use alloc::vec::Vec;
}

// Pokemon-specific modules (not in dotzuki-renderer)
pub mod embedded;
pub mod hash_compat;
pub mod screen_fade;
mod resource_catalog;
// Bare-metal (GBA) pre-converted asset registry generated by build.rs.
#[cfg(target_os = "none")]
pub mod gba_assets {
    include!(concat!(env!("OUT_DIR"), "/gba_assets.rs"));
}
// Pokered asset-name override of the engine's `mon_icon` loader — shadows the
// glob re-export above so `pokered_renderer::mon_icon::load_mon_icon_tiles`
// resolves the party icons against the real pret/pokered gfx files.
pub mod mon_icon;
#[cfg(all(feature = "gpu", not(target_os = "none")))]
pub mod resource;
// Bare-metal stand-in for `resource` under the framebuffer feature: same
// named load helpers, backed by the build-time pre-converted 2bpp/1bpp
// registry instead of runtime PNG decoding.
#[cfg(all(target_os = "none", feature = "framebuffer"))]
#[path = "resource_gba.rs"]
pub mod resource;

#[cfg(test)]
mod tests;
