[package]
name = "pokered-data"
version.workspace = true
edition.workspace = true

[features]
default = []
serde = []
embedded-map-data = []

[dependencies]
dotzuki-engine-script = { git = "https://github.com/liuyanghejerry/dotzuki", tag = "v0.5.6" }
dotzuki-engine-dsl = { git = "https://github.com/liuyanghejerry/dotzuki", tag = "v0.5.6" }
boa_engine = { version = "0.20", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
log = "0.4"
dotzuki-engine = { git = "https://github.com/liuyanghejerry/dotzuki", tag = "v0.5.6" }
dotzuki-renderer = { git = "https://github.com/liuyanghejerry/dotzuki", tag = "v0.5.6" }

[dev-dependencies]
ron = { workspace = true }

[build-dependencies]
serde_json = { workspace = true }
dotzuki-engine-dsl = { git = "https://github.com/liuyanghejerry/dotzuki", tag = "v0.5.6" }
