[package]
name = "pokered-debug-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dotzuki-app = { git = "https://github.com/liuyanghejerry/dotzuki", rev = "162182fde89e414414ac9e9ba0e9a5051804b16d" }
serde = { workspace = true }
serde_json = { workspace = true }
