[package]
name = "pokered-debug-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dotzuki-app = { git = "https://github.com/liuyanghejerry/dotzuki", rev = "366e5026e872466305b8b338082a8de9f7969b5b" }
serde = { workspace = true }
serde_json = { workspace = true }
