[package]
name = "pokered-debug-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dotzuki-app = { git = "https://github.com/liuyanghejerry/dotzuki", rev = "a18bacf1cf6f7bfd9c20439abcf0745ad25d7057" }
serde = { workspace = true }
serde_json = { workspace = true }
