#!/usr/bin/env python3
"""Build the small dialogue word list from shipped Chinese text.

Development-only dependency: jieba==0.42.1 (MIT). No tokenizer or dictionary
is loaded by the game. Regenerate after adding dialogue vocabulary; --check
verifies the checked-in output. Existing English/Chinese dialogue is untouched.
"""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
LITERAL = r'"((?:[^"\\]|\\.)*)"'
PAIRS = re.compile(r'(?:@t|game\.t)\(\s*' + LITERAL + r'\s*,\s*' + LITERAL + r'\s*\)')
HAN_WORD = re.compile(r'[\u3400-\u9fff]+\Z')


def main():
    import jieba
    if jieba.__version__ != "0.42.1":
        raise SystemExit("Use jieba==0.42.1 for reproducible generation")
    texts = []
    for path in sorted((ROOT / 'crates/pokered-data/maps').rglob('*.scene')):
        texts.extend(json.loads('"' + m[2] + '"') for m in PAIRS.finditer(path.read_text()))
    source = (ROOT / 'crates/pokered-data/src/dialog_text.rs').read_text()
    texts.extend(json.loads('"' + m[2] + '"') for m in re.finditer(r'\(' + LITERAL + r',\s*' + LITERAL + r'\)', source))
    for filename in ['ui_text.rs', 'battle_text.rs']:
        source = (ROOT / 'crates/pokered-data/src' / filename).read_text().split('#[cfg(test)]')[0]
        texts.extend(json.loads('"' + m[1] + '"') for m in re.finditer(LITERAL, source)
                     if re.search(r'[\u3400-\u9fff]', m[1]))
    for path in sorted((ROOT / 'crates/pokered-data/pokemon').glob('*.json')):
        dex = json.loads(path.read_text()).get('pokedex', {})
        texts.extend(dex.get('flavorTextPagesZh', []))
        texts.append(dex.get('categoryZh', ''))
    # Include shipped introductory/UI/system text, excluding test examples.
    for tree in ['crates/pokered-core/src', 'crates/pokered-ui/src', 'crates/pokered-app/src/render']:
        for path in sorted((ROOT / tree).rglob('*.rs')):
            source = path.read_text().split('#[cfg(test)]')[0]
            for match in re.finditer(LITERAL, source):
                try:
                    text = json.loads('"' + match[1] + '"')
                except json.JSONDecodeError:
                    continue
                if re.search(r'[\u3400-\u9fff]', text):
                    texts.append(text)
    names = []
    for filename in ['lang_data.rs', 'map_names.rs']:
        names.extend(re.findall(r'"([\u3400-\u9fff]{2,14})"', (ROOT / 'crates/pokered-data/src' / filename).read_text()))
    # Game-specific terms supplement general Chinese segmentation.
    names.extend('宝可梦 宝可梦中心 宝可梦联盟 大木博士 精灵球 火箭队 西尔佛公司 联机俱乐部 训练家 图鉴完成度 探宝器 小智 小茂 好好 保护自己 自行车道'.split())
    tokenizer = jieba.Tokenizer()
    for word in names:
        tokenizer.add_word(word, freq=1000000)
    words = set(names)
    for text in texts:
        # Authored single newlines in CJK are soft wrapping, not word boundaries.
        for paragraph in re.split(r'\n\s*\n', text):
            paragraph = re.sub(r'(?<=[\u3400-\u9fff])\n(?=[\u3400-\u9fff])', '', paragraph)
            words.update(tokenizer.cut(paragraph.replace('\n', ' '), HMM=False))
    words = sorted(w for w in words if HAN_WORD.fullmatch(w) and 2 <= len(w) <= 14)
    output = '// Generated by scripts/generate_zh_dialogue_words.py (jieba 0.42.1).\n'
    output += '// Words are drawn from game dialogue/name tables; runtime uses no NLP dependency.\n'
    output += 'pub const WORDS: &[&str] = &[\n'
    output += ''.join('    ' + json.dumps(w, ensure_ascii=False) + ',\n' for w in words)
    output += '];\n'
    output += f'pub const MAX_WORD_CHARS: usize = {max(map(len, words))};\n'
    path = ROOT / 'crates/pokered-data/src/zh_dialogue_words.rs'
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        if path.read_text() != output:
            raise SystemExit('Chinese dialogue word list is stale; regenerate it')
    else:
        path.write_text(output)
    print(f'{len(words)} protected words from {len(texts)} localized literals')


if __name__ == '__main__':
    main()
