#!/usr/bin/env python3
"""Generate the trainer-victory-quip EN→ZH table (battle_quips.rs).

Keys must match `npcs[].endBattleText` in maps/*/map.json byte-for-byte
(verified against the data below)."""
import json, glob

Q = {
'Aaaargh!': '啊——！',
'Aack!\nBrothers, I lost!': '呀！\n兄弟们，我输了！',
'Aiyah!': '哎呀！',
'All\nwarmed up!': '正好\n热身了！',
'Are you\nsatisfied?': '你满意了吗？',
'Argh!\nBeaten by a kid!': '啊！\n竟然输给小孩子！',
'Argh!\nLost it!': '啊！\n输了！',
'Arrg!\nLost! Get lost!': '啊！输了！\n一边去！',
'Arrgh!': '啊——！',
'Arrrgh!': '啊——！',
"Atcha!\nDidn't go my way!": '嘿呀！\n没能如愿！',
'Atcho!': '嘿咻！',
'Awoo!': '呜哇！',
'Awooh!': '呜噢！',
'Aww,\nbummer!': '哎，\n真倒霉！',
'Aww,\ndarn...': '哎，\n可恶……',
'Ayah!': '呀！',
'Ayaya!': '呀呀！',
'Bad,\nbad, bad!': '糟糕，\n糟糕，太糟糕！',
'Be nice!': '放规矩点！',
'Belly\nflop!': '摔了个\n大马趴！',
'Blown\naway!': '被打飞了！',
'Boom!': '砰！',
'Burned\nagain!': '又被烧了！',
'Burned\nout!': '烧起来了！',
'Burnt!': '烧焦了！',
"Can't\nmeasure up!": '根本\n不是对手！',
'Cheap\nshot!': '卑鄙！',
'Cough...\nCough...': '咳……\n咳……',
'Crash and\nburn!': '一败涂地！',
'Dang!': '可恶！',
'Dang!\nBlast it!': '可恶！\n见鬼！',
'Dang!\nStripped gears!': '可恶！\n机器都散架了！',
'Darn\nMAGIKARP!': '可恶的\n鲤鱼王！',
'Darn!': '可恶！',
"Darn!\n\nLight years isn't\ntime! It measures\ndistance!": '可恶！\n\n光年是距离单位！\n根本不是时间！',
'Darn!\nI let that one\nget away!': '可恶！\n让它给\n跑了！',
'Darn!\nI need to make my\nPOKeMON stronger!': '可恶！\n得把宝可梦\n练得更强才行！',
'Darn!\nYou weak POKeMON!': '可恶！\n你这没用的宝可梦！',
'Diver!!\nDown!!': '跳水！\n下潜！',
'Doh!\nYou win!': '哦！\n你赢了！',
"Don't\nfight us ROCKETs!": '别跟火箭队\n作对！',
"Don't\ntouch my pearls!": '别碰\n我的珍珠！',
"Don't make\nme mad!": '别把我\n惹急了！',
"Don't you\ndare laugh!": '你敢笑！',
"Don't...\nPlease!": '别这样……\n求你了！',
'Done\nlike dinner!': '彻底\n完蛋了！',
'Drat!\nCame up short!': '见鬼！\n就差一点！',
'Dropped\nmy balls!': '我的球\n掉了！',
'Ease up!\nWhat am I doing?\nWhich way is out?': '轻点！\n我在干什么？\n出口在哪边？',
'Fine!\nI lost!': '行！\n我输了！',
'Fired\naway!': '发射！',
'Flame\nout!': '火焰\n熄灭了！',
'Fried!': '烤熟了！',
'Gaah!\nDemolished!': '嘎！\n被拆得稀烂！',
'Game\nover!': '游戏\n结束！',
'Gasp!': '倒吸一口气！',
'Ghaaah!': '嘎——！',
'Glub!': '咕噜！',
'Good\nfight! Ah, I feel\nyoung again!': '打得漂亮！\n啊，我仿佛\n回到了年轻的时候！',
'Groan!': '哼！',
'Grounded\nout!': '出局了！',
'Ha-haha!\nNot laughing!\nHa-hay fever!\nHaha-ha-choo!': '哈-哈哈！\n我可不是在笑！\n是花粉症！\n哈哈-啊嚏！',
'Ha?': '哈？',
'Hahahaha!\nYou beat me fair!': '哈哈哈！\n你赢得堂堂正正！',
'Help!': '救命！',
'Hmm?\nWhat am I doing?': '嗯？\n我在干什么来着？',
'How\ndid you know I\nwas a ROCKET?': '你怎么知道\n我是火箭队的？',
'How could I\nlose?': '我怎么可能\n输呢？',
'Huh?\nI lost?': '咦？\n我输了？',
'Huh?\nI ran out of\nPOKeMON!': '咦？\n我的宝可梦\n全倒下了！',
"Huh?\nThat's not right!": '咦？\n不对劲！',
'Huh?\nWho? What?': '咦？\n谁？什么？',
'Humph!\nYou rude child!': '哼！\n没礼貌的小孩！',
"Humph.\nI'm not angry!": '哼。\n我才没生气！',
"Hwa!\nI'm saved!": '哇！\n得救了！',
"I\ncan't do it!": '我\n做不到！',
"I\ndidn't start it!": '不是我\n先动手的！',
"I\ndon't believe it!": '我\n不敢相信！',
"I\ngive! You're good\nat this!": '我认输！\n你真有\n两下子！',
'I\nhad a chance...': '我本来\n有机会的……',
'I\nhad to bug you!': '我非来\n缠你不可！',
"I\njust can't win!": '我\n就是赢不了！',
'I\nknew it!': '我\n就知道！',
'I\nlost my grip!': '我\n失手了！',
'I\nlost out!': '我\n输掉了！',
'I\nlost.': '我\n输了。',
'I\nran out of gas!': '我\n没力气了！',
'I\nsaid trade!': '我说了\n要交换！',
'I\nsurrender!': '我\n投降！',
'I\nthought not!': '我\n就知道会这样！',
'I\nwas beaten?': '我\n被打败了？',
'I blew\nit!': '我搞砸了！',
"I didn't\nask for this!": '我可没\n要求这样！',
"I don't\nbelieve it!": '我不敢\n相信！',
"I don't\nbelieve this!": '我不敢\n相信这是真的！',
'I give\nup!': '我放弃\n了！',
'I give up!': '我认输了！',
'I give!': '我认输！',
"I give!\nYou're a better\ntechnician!": '我认输！\n你的技术\n更胜一筹！',
'I goofed!': '我搞砸了！',
'I got\nwhipped!': '我被\n打得落花流水！',
'I had\na chance!': '我本来\n有机会的！',
"I knew\nI'd lose too!": '我就知道\n我也会输！',
'I knew\nit!': '我\n就知道！',
'I lost\nafter all!': '我终究\n还是输了！',
'I lost\nmy concentration!': '我走神\n了！',
'I lost\ntoo!': '我也\n输了！',
'I lost?': '我输了？',
'I must\nsalute you!': '我必须\n向你致敬！',
'I never\nforesaw this!': '我从未\n料到会这样！',
'I saw\nthis coming...': '我早料到\n会有这一天……',
'I was\njust careless!': '我只是\n大意了！',
'I was\ntoo impatient!': '我太\n急躁了！',
'I was in\nbad condition!': '我的状态\n太差了！',
"I'll\nstay with school.": '我还是要\n专心读书。',
"I'm\nall out!": '我\n全军覆没了！',
"I'm\ndone!": '我\n完蛋了！',
"I'm\nexhausted...": '我\n筋疲力尽……',
"I'm\nfurious!": '我\n气疯了！',
"I'm\nin shock!": '我\n惊呆了！',
"I'm\nnot mad!": '我\n没生气！',
"I'm\nnot so jealous!": '我也没那么\n嫉妒你！',
"I'm\nnot up to it!": '我不够\n资格！',
"I'm\nout of POKeMON!": '我的宝可梦\n全倒下了！',
"I'm\nso disappointed!": '我太\n失望了！',
"I'm\nsteamed!": '我\n火了！',
"I'm\nstunned!": '我\n被震惊了！',
"I'm done\nfor!": '我彻底\n完了！',
"If I\nhad new POKeMON I\nwould've won!": '要是我有新的\n宝可梦，\n赢的就是我！',
'It\nwas too dark!': '这里\n太黑了！',
"It's\nnot easy...": '这可不容易……',
"It's\nnot logical!": '这不合逻辑！',
"It's over\nalready?": '这就\n结束了？',
'Judge!\n1 point!': '裁判！\n给1分！',
'Just\nas I thought!': '正如\n我所料！',
"Just\ndidn't work!": '就是\n行不通！',
'Just\nmessed up!': '就是\n失手了！',
'Kaboom!': '轰隆！',
'Keee!': '吱——！',
"Keep it\ncoming, eh!\n\nOh wait. I'm out\nof POKeMON!": '放马过来啊！\n\n啊等等，我的\n宝可梦全倒下了！',
'Knock\nout!': '击倒\n出局！',
'Lights\nout!': '熄灯\n出局！',
'Look what\nyou did!': '看看你干的\n好事！',
'Losing\nstinks!': '输的滋味\n真难受！',
'Lost\nit!': '输了！',
'Lost!\nLost! Lost!': '输了！\n输了！输了！',
'Meow!': '喵！',
'Missed\nthe big score!': '错过了\n发大财的机会！',
"My\nPOKeMON couldn't!": '我的宝可梦\n顶不住了！',
"My\nPOKeMON won't do!": '我的宝可梦\n不听使唤！',
'My\nbird combo lost?': '我的鸟儿组合\n输了？',
'My\nbugs...': '我的虫儿们……',
'My\nfirst loss!': '这是我的\n首败！',
'My\nmakeup!': '我的妆！',
'My, my\nfriends...': '哎呀，\n朋友们……',
'No\ncontinues left!': '没有续关\n机会了！',
'No\nmercy at all!': '一点都不\n留情面！',
'No!': '不！',
"No!\nCATERPIE can't\ncut it!": '不！\n绿毛虫顶\n不住了！',
'No!\nUnbelievable!': '不！\n难以置信！',
"No!\nYou're kidding!": '不！\n你在开玩笑吧！',
"No!\nYou're too much!": '不！\n你也太狠了！',
'No,\nwrong!': '不，\n不对！',
'Not\nenough grit!': '毅力\n不够！',
'Not\nenough!': '还\n不够！',
'Not\ngood enough!': '还不够\n水平！',
'Not\nready yet!': '我还没\n准备好！',
"OK, \nyou're not bad.": '行，\n你还不赖。',
'Oh\ngoodness!': '我的\n天哪！',
'Oh\nno!': '不好\n了！',
"Oh ho!\nYou're something\nspecial, child!": '哦呵！\n小朋友，你可是\n相当厉害啊！',
'Oh no!\nI went around the\nworld for these!': '不！\n我可是环游了世界\n才收集到这些的！',
'Oh no!\nMy POKeMON!': '不好！\n我的宝可梦！',
'Oh no!\nMy bag of loot!': '不好！\n我装赃物的袋子！',
'Oh!\nBeaten!': '哦！\n被打败了！',
'Oh!\nI lost it!': '哦！\n我输了！',
'Oh!\nI lost!': '哦！\n我输了！',
'Oh!\nSo strong!': '哦！\n好强！',
'Oh!\nSplendid!': '哦！\n精彩！',
'Oh!\nYou little brute!': '哦！\n你这个小蛮牛！',
'Oh!\nYou!': '哦！\n是你！',
'Oh! My cute\nmushroom POKeMON!': '哦！我可爱的\n蘑菇宝可梦！',
'Ohh!\nBlew it again!': '噢！\n又搞砸了！',
'Ohh!\nI lost!': '噢！\n我输了！',
'Ohhh!\nI did my best!': '噢——！\n我尽力了！',
'Oof!\nI give up!': '喔！\n我认输了！',
'Oof!\nTaken down!': '喔！\n被撂倒了！',
'Ooh!\nDangerous!': '嚯！\n真危险！',
"Ooh!\nThat's chilly!": '嚯！\n好冷啊！',
'Ooh!\nTraumatic!': '嚯！\n留下心理阴影了！',
'Oops!\nOut-muscled!': '哎呀！\n力气上输了！',
'Ouch!': '哎哟！',
'Ouch!\nTorpedoed!': '哎哟！\n被鱼雷击中了！',
'Out\nlike a light!': '一下就\n昏过去了！',
'Out\nof power!': '没电\n了！',
'Ow!\nMeltdown!': '哎哟！\n熔化了！',
'Ow!\nStomped flat!': '哎哟！\n被踩扁了！',
"Ow!\nThat's tragic!": '哎哟！\n太惨了！',
'Oww!': '哎哟哟！',
'Oww!\nBeaten!': '哎哟！\n被打败了！',
'Pant...\npant...pant...': '呼……\n呼……呼……',
'Please!\nNo more!': '求你了！\n别打了！',
'Quit it!': '住手！',
'Right!\nGood fight, mate!': '没错！\n打得漂亮，伙计！',
'Shocker!': '电了一下！',
'Shoot!': '糟了！',
"Shoot!\nI'm so jealous!": '糟了！\n我太羡慕了！',
'Shot\ndown in flames!': '被打得\n落花流水！',
'Smoked!': '被熏倒了！',
'So, you\nare good.': '看来你\n确实厉害。',
'Some-\nthing fell out!': '有什么东西\n掉出来了！',
"Sorry!\nI didn't mean it!": '对不起！\n我不是故意的！',
'Splash!': '跃起！',
"Stop!\n\nDon't be so mean\nto my CLEFAIRY!": '住手！\n\n别对我的皮皮\n那么狠！',
"Stop!\nYou're very good!": '住手！\n你实在太强了！',
'Take\nit easy!': '手下留情！',
'Tch!': '切！',
'Tch!\nJust a small fry!': '切！\n不过是条小鱼！',
'That\nburned some time.': '就这么\n耗掉了一些时间。',
"That\ncan't be true!": '那不可能是\n真的！',
"That\ncan't be!": '不可能！',
'That\ncleared my head!': '这一战让我\n头脑清醒了！',
'That\none got away!': '那一只\n逃掉了！',
'That\nwas electric!': '刚才那一下\n够带电的！',
"That's it?": '就这样？',
'The\nrumors were true!': '传言\n果然是真的！',
'The\nwind turned!': '风向\n变了！',
"This\nwon't do!": '这样下去\n可不行！',
'Too\nmuch!': '太过分\n了！',
'Too\nmuch, too young!': '年纪轻轻，\n下手太狠！',
'Tough!': '真难缠！',
'Ugh!\nI hate losing!': '呃！\n我讨厌输！',
'Unplugged!': '被拔了插头！',
"Urgh!\nNow I'm mad!": '呃！\n这下我火了！',
'WHAT?\n\nWhat a total\nwaste of time!': '什么？\n\n完全是\n浪费时间！',
'Wait!': '等等！',
'Warg!\nBrothers, I lost!': '呜啊！\n兄弟们，我输了！',
'Wargh!': '呜啊——！',
'Well\ndone!': '干得\n漂亮！',
"Well,\nthat's that.": '好吧，\n就这样吧。',
'What\na nightmare!': '真是\n一场噩梦！',
'What\nwas that for?': '你这是\n干什么？',
'What!': '什么！',
"What's\nthat?": '那是\n什么？',
'What?\nExtraordinary!': '什么？\n不可思议！',
'What?\nI lost? No!': '什么？\n我输了？不会吧！',
'What?\nYou!?': '什么？\n是你！？',
'Where\nis the GHOST?': '幽灵\n在哪里？',
'Whew!\nGood workout!': '呼！\n真是一场好锻炼！',
"Whew!\nI'm exhausted!": '呼！\n我累坏了！',
'Whew!\nOverwhelming!': '呼！\n简直无法招架！',
'Whew!\nThe spirit left!': '呼！\n灵魂离开身体了！',
'Who\nare you?': '你是\n谁？',
"Whoa!\nHe's got it!": '喔！\n他来真的了！',
'Whoa!\nToo much!': '喔！\n太狠了！',
'Whoa!\nYou spark plug!': '喔！\n你这个小火花塞！',
'Whoo!': '呼喔！',
'Whoo!\nGood stuff!': '呼喔！\n真有两下子！',
'Whoo!\nOh brothers!': '呼喔！\n我的天哪！',
'Why\nnot?': '有什么\n不可以？',
'Why,\nyou!': '好你个\n小子！',
'Why...?': '为什么……？',
'Why?\nHow could I lose?': '为什么？\n我怎么可能输？',
"Why?\nWhy'd I lose?": '为什么？\n我为什么会输？',
'Why? Why??': '为什么？为什么？？',
'Wimpy!': '真没用！',
'Wipe out!': '全军覆没！',
'Wow!\nShocked again!': '哇！\n又被电了！',
'Wow!\nSurprised me!': '哇！\n吓了我一跳！',
'Wow!\nYou totally won!': '哇！\n你赢得彻彻底底！',
"Wow! \nYou're great!": '哇！\n你真厉害！',
'You\nare too good!': '你\n实在太强了！',
'You\nbeat me again!': '你又\n打败我了！',
'You\ndeceived me!': '你骗了\n我！',
'You\ngot me!': '你\n赢了我！',
'You\ngot me.': '你赢了。',
'You\nhad me fooled!': '我被你\n耍了！',
'You\nhammered me!': '你把我\n打得稀烂！',
'You\nlittle rat!': '你这个小\n滑头！',
'You\noverwhelmed me!': '你让我\n毫无还手之力！',
'You\nplay hard!': '你打得很拼！',
'You\nreally got me!': '你真的\n赢了我！',
'You\ntraitor!': '你这个\n叛徒！',
'You\nworked hard!': '你很\n努力！',
'You are in\nperfect harmony!': '你和宝可梦\n配合得天衣无缝！',
'You looked\nso cute too!': '你刚才看起来\n还挺可爱的！',
"You're\ndecent.": '你还\n不错。',
"You're\ngood.": '你\n很强。',
"You're\nimpressive!": '你让人\n刮目相看！',
"You're\nmean!": '你真\n坏！',
"You're\nsomething.": '你真\n不简单。',
"You're\ntoo rough!": '你也太\n狠了！',
'Your\nspirit sank me!': '你的气势\n把我压垮了！',
'Yow!\nI lost!': '哟！\n我输了！',
'Yow!\nStubbed fingers!': '哟！\n手指戳到了！',
'Yowch!': '哎哟喂！',
'Yowch!\nWhiplash!': '哎哟喂！\n闪到脖子了！',
}

def main():
    # Collect the actual data.
    texts = set()
    for f in glob.glob('crates/pokered-data/maps/*/map.json'):
        try:
            data = json.load(open(f))
        except Exception:
            continue
        for npc in data.get('npcs', []):
            t = npc.get('endBattleText')
            if t and t.strip():
                texts.add(t)

    missing = sorted(t for t in texts if t not in Q)
    extra = sorted(k for k in Q if k not in texts)
    if missing:
        print("MISSING TRANSLATIONS:")
        for m in missing:
            print(" ", repr(m))
    if extra:
        print("KEYS NOT IN DATA (typos?):")
        for e in extra:
            print(" ", repr(e))
    if missing or extra:
        raise SystemExit(1)

    lines = [
        "//! Trainer victory quips (data-driven `endBattleText` from the map",
        "//! JSON), translated exactly. Keys must match the stored English",
        "//! byte-for-byte; regenerate via tools/gen_battle_quips.py.",
        "",
        "pub const QUIPS: &[(&str, &str)] = &[",
    ]
    for k in sorted(Q):
        zk = Q[k]
        def esc(s):
            return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        lines.append(f'    ("{esc(k)}", "{esc(zk)}"),')
    lines.append("];")
    lines.append("")
    with open('crates/pokered-data/src/battle_quips.rs', 'w') as w:
        w.write("\n".join(lines))
    print(f"Wrote {len(Q)} entries.")

if __name__ == '__main__':
    main()
