//! Language-dependent name tables. Use `is_zh: true` for Chinese, `false` for English.

use crate::moves::MoveId;
use crate::species::Species;
use crate::types::PokemonType;

const SPECIES_ZH: &[&str] = &[
    "",
    "妙蛙种子","妙蛙草","妙蛙花","小火龙","火恐龙","喷火龙","杰尼龟","卡咪龟","水箭龟",
    "绿毛虫","铁甲蛹","巴大蝶","独角虫","铁壳蛹","大针蜂","波波","比比鸟","大比鸟",
    "小拉达","拉达","烈雀","大嘴雀","阿柏蛇","阿柏怪","皮卡丘","雷丘","穿山鼠","穿山王",
    "尼多兰","尼多娜","尼多后","尼多朗","尼多力诺","尼多王","皮皮","皮可西","六尾","九尾",
    "胖丁","胖可丁","超音蝠","大嘴蝠","走路草","臭臭花","霸王花","派拉斯","派拉斯特",
    "毛球","末入蛾","地鼠","三地鼠","喵喵","猫老大","可达鸭","哥达鸭","猴怪","火暴猴",
    "卡蒂狗","风速狗","蚊香蝌蚪","蚊香君","蚊香泳士","凯西","勇基拉","胡地","腕力","豪力",
    "怪力","喇叭芽","口呆花","大食花","玛瑙水母","毒刺水母","小拳石","隆隆石","隆隆岩",
    "小火马","烈焰马","呆呆兽","呆壳兽","小磁怪","三合一磁怪","大葱鸭","嘟嘟","嘟嘟利",
    "小海狮","白海狮","臭泥","臭臭泥","大舌贝","刺甲贝","鬼斯","鬼斯通","耿鬼","大岩蛇",
    "催眠貘","引梦貘人","大钳蟹","巨钳蟹","霹雳电球","顽皮雷弹","蛋蛋","椰蛋树",
    "卡拉卡拉","嘎啦嘎啦","飞腿郎","快拳郎","大舌头","瓦斯弹","双弹瓦斯","铁甲犀牛",
    "铁甲暴龙","吉利蛋","蔓藤怪","袋兽","墨海马","海刺龙","角金鱼","金鱼王","海星星",
    "宝石海星","魔墙人偶","飞天螳螂","迷唇姐","电击兽","鸭嘴火兽","凯罗斯","肯泰罗",
    "鲤鱼王","暴鲤龙","拉普拉斯","百变怪","伊布","水伊布","雷伊布","火伊布","多边兽",
    "菊石兽","多刺菊石兽","化石盔","镰刀盔","化石翼龙","卡比兽","急冻鸟","闪电鸟",
    "火焰鸟","迷你龙","哈克龙","快龙","超梦","梦幻",
];

pub fn species_name(s: Species, is_zh: bool) -> &'static str {
    if is_zh {
        SPECIES_ZH.get(s as usize).copied().unwrap_or("???")
    } else {
        species_name_en(s)
    }
}

fn species_name_en(s: Species) -> &'static str {
    match s {
        Species::None=>"---",
        Species::Bulbasaur=>"BULBASAUR",Species::Ivysaur=>"IVYSAUR",Species::Venusaur=>"VENUSAUR",
        Species::Charmander=>"CHARMANDER",Species::Charmeleon=>"CHARMELEON",Species::Charizard=>"CHARIZARD",
        Species::Squirtle=>"SQUIRTLE",Species::Wartortle=>"WARTORTLE",Species::Blastoise=>"BLASTOISE",
        Species::Caterpie=>"CATERPIE",Species::Metapod=>"METAPOD",Species::Butterfree=>"BUTTERFREE",
        Species::Weedle=>"WEEDLE",Species::Kakuna=>"KAKUNA",Species::Beedrill=>"BEEDRILL",
        Species::Pidgey=>"PIDGEY",Species::Pidgeotto=>"PIDGEOTTO",Species::Pidgeot=>"PIDGEOT",
        Species::Rattata=>"RATTATA",Species::Raticate=>"RATICATE",Species::Spearow=>"SPEAROW",
        Species::Fearow=>"FEAROW",Species::Ekans=>"EKANS",Species::Arbok=>"ARBOK",
        Species::Pikachu=>"PIKACHU",Species::Raichu=>"RAICHU",Species::Sandshrew=>"SANDSHREW",
        Species::Sandslash=>"SANDSLASH",Species::NidoranF=>"NIDORAN♀",Species::Nidorina=>"NIDORINA",
        Species::Nidoqueen=>"NIDOQUEEN",Species::NidoranM=>"NIDORAN♂",Species::Nidorino=>"NIDORINO",
        Species::Nidoking=>"NIDOKING",Species::Clefairy=>"CLEFAIRY",Species::Clefable=>"CLEFABLE",
        Species::Vulpix=>"VULPIX",Species::Ninetales=>"NINETALES",Species::Jigglypuff=>"JIGGLYPUFF",
        Species::Wigglytuff=>"WIGGLYTUFF",Species::Zubat=>"ZUBAT",Species::Golbat=>"GOLBAT",
        Species::Oddish=>"ODDISH",Species::Gloom=>"GLOOM",Species::Vileplume=>"VILEPLUME",
        Species::Paras=>"PARAS",Species::Parasect=>"PARASECT",Species::Venonat=>"VENONAT",
        Species::Venomoth=>"VENOMOTH",Species::Diglett=>"DIGLETT",Species::Dugtrio=>"DUGTRIO",
        Species::Meowth=>"MEOWTH",Species::Persian=>"PERSIAN",Species::Psyduck=>"PSYDUCK",
        Species::Golduck=>"GOLDUCK",Species::Mankey=>"MANKEY",Species::Primeape=>"PRIMEAPE",
        Species::Growlithe=>"GROWLITHE",Species::Arcanine=>"ARCANINE",Species::Poliwag=>"POLIWAG",
        Species::Poliwhirl=>"POLIWHIRL",Species::Poliwrath=>"POLIWRATH",Species::Abra=>"ABRA",
        Species::Kadabra=>"KADABRA",Species::Alakazam=>"ALAKAZAM",Species::Machop=>"MACHOP",
        Species::Machoke=>"MACHOKE",Species::Machamp=>"MACHAMP",Species::Bellsprout=>"BELLSPROUT",
        Species::Weepinbell=>"WEEPINBELL",Species::Victreebel=>"VICTREEBEL",Species::Tentacool=>"TENTACOOL",
        Species::Tentacruel=>"TENTACRUEL",Species::Geodude=>"GEODUDE",Species::Graveler=>"GRAVELER",
        Species::Golem=>"GOLEM",Species::Ponyta=>"PONYTA",Species::Rapidash=>"RAPIDASH",
        Species::Slowpoke=>"SLOWPOKE",Species::Slowbro=>"SLOWBRO",Species::Magnemite=>"MAGNEMITE",
        Species::Magneton=>"MAGNETON",Species::Farfetchd=>"FARFETCH'D",Species::Doduo=>"DODUO",
        Species::Dodrio=>"DODRIO",Species::Seel=>"SEEL",Species::Dewgong=>"DEWGONG",
        Species::Grimer=>"GRIMER",Species::Muk=>"MUK",Species::Shellder=>"SHELLDER",
        Species::Cloyster=>"CLOYSTER",Species::Gastly=>"GASTLY",Species::Haunter=>"HAUNTER",
        Species::Gengar=>"GENGAR",Species::Onix=>"ONIX",Species::Drowzee=>"DROWZEE",
        Species::Hypno=>"HYPNO",Species::Krabby=>"KRABBY",Species::Kingler=>"KINGLER",
        Species::Voltorb=>"VOLTORB",Species::Electrode=>"ELECTRODE",Species::Exeggcute=>"EXEGGCUTE",
        Species::Exeggutor=>"EXEGGUTOR",Species::Cubone=>"CUBONE",Species::Marowak=>"MAROWAK",
        Species::Hitmonlee=>"HITMONLEE",Species::Hitmonchan=>"HITMONCHAN",Species::Lickitung=>"LICKITUNG",
        Species::Koffing=>"KOFFING",Species::Weezing=>"WEEZING",Species::Rhyhorn=>"RHYHORN",
        Species::Rhydon=>"RHYDON",Species::Chansey=>"CHANSEY",Species::Tangela=>"TANGELA",
        Species::Kangaskhan=>"KANGASKHAN",Species::Horsea=>"HORSEA",Species::Seadra=>"SEADRA",
        Species::Goldeen=>"GOLDEEN",Species::Seaking=>"SEAKING",Species::Staryu=>"STARYU",
        Species::Starmie=>"STARMIE",Species::MrMime=>"MR.MIME",Species::Scyther=>"SCYTHER",
        Species::Jynx=>"JYNX",Species::Electabuzz=>"ELECTABUZZ",Species::Magmar=>"MAGMAR",
        Species::Pinsir=>"PINSIR",Species::Tauros=>"TAUROS",Species::Magikarp=>"MAGIKARP",
        Species::Gyarados=>"GYARADOS",Species::Lapras=>"LAPRAS",Species::Ditto=>"DITTO",
        Species::Eevee=>"EEVEE",Species::Vaporeon=>"VAPOREON",Species::Jolteon=>"JOLTEON",
        Species::Flareon=>"FLAREON",Species::Porygon=>"PORYGON",Species::Omanyte=>"OMANYTE",
        Species::Omastar=>"OMASTAR",Species::Kabuto=>"KABUTO",Species::Kabutops=>"KABUTOPS",
        Species::Aerodactyl=>"AERODACTYL",Species::Snorlax=>"SNORLAX",Species::Articuno=>"ARTICUNO",
        Species::Zapdos=>"ZAPDOS",Species::Moltres=>"MOLTRES",Species::Dratini=>"DRATINI",
        Species::Dragonair=>"DRAGONAIR",Species::Dragonite=>"DRAGONITE",Species::Mewtwo=>"MEWTWO",
        Species::Mew=>"MEW",
        _ => "???", // species added through the editor (no localized name yet)
    }
}

pub fn type_name(t: PokemonType, is_zh: bool) -> &'static str {
    if is_zh {
        match t {
            PokemonType::Normal=>"一般",PokemonType::Fighting=>"格斗",PokemonType::Flying=>"飞行",
            PokemonType::Poison=>"毒",PokemonType::Ground=>"地面",PokemonType::Rock=>"岩石",
            PokemonType::Bird=>"鸟",PokemonType::Bug=>"虫",PokemonType::Ghost=>"幽灵",
            PokemonType::Fire=>"火",PokemonType::Water=>"水",PokemonType::Grass=>"草",
            PokemonType::Electric=>"电",PokemonType::Psychic=>"超能力",PokemonType::Ice=>"冰",
            PokemonType::Dragon=>"龙",
        }
    } else {
        match t {
            PokemonType::Normal=>"NORMAL",PokemonType::Fighting=>"FIGHTING",PokemonType::Flying=>"FLYING",
            PokemonType::Poison=>"POISON",PokemonType::Ground=>"GROUND",PokemonType::Rock=>"ROCK",
            PokemonType::Bird=>"BIRD",PokemonType::Bug=>"BUG",PokemonType::Ghost=>"GHOST",
            PokemonType::Fire=>"FIRE",PokemonType::Water=>"WATER",PokemonType::Grass=>"GRASS",
            PokemonType::Electric=>"ELECTRIC",PokemonType::Psychic=>"PSYCHIC",PokemonType::Ice=>"ICE",
            PokemonType::Dragon=>"DRAGON",
        }
    }
}

pub fn move_name(m: MoveId, is_zh: bool) -> &'static str {
    if is_zh {
        match m {
            MoveId::Pound=>"拍击",MoveId::KarateChop=>"空手劈",MoveId::Doubleslap=>"连环巴掌",
            MoveId::CometPunch=>"连续拳",MoveId::MegaPunch=>"百万吨拳击",MoveId::PayDay=>"聚宝功",
            MoveId::FirePunch=>"火焰拳",MoveId::IcePunch=>"冰冻拳",MoveId::Thunderpunch=>"雷电拳",
            MoveId::Scratch=>"抓",MoveId::Vicegrip=>"夹住",MoveId::Guillotine=>"断头钳",
            MoveId::RazorWind=>"旋风刀",MoveId::SwordsDance=>"剑舞",MoveId::Cut=>"居合斩",
            MoveId::Gust=>"起风",MoveId::WingAttack=>"翅膀攻击",MoveId::Whirlwind=>"吹飞",
            MoveId::Fly=>"飞翔",MoveId::Bind=>"绑紧",MoveId::Slam=>"摔打",MoveId::VineWhip=>"藤鞭",
            MoveId::Stomp=>"踩踏",MoveId::DoubleKick=>"二连踢",MoveId::MegaKick=>"百万吨踢击",
            MoveId::JumpKick=>"飞踢",MoveId::RollingKick=>"回旋踢",MoveId::SandAttack=>"泼沙",
            MoveId::Headbutt=>"头锤",MoveId::HornAttack=>"角撞",MoveId::FuryAttack=>"乱击",
            MoveId::HornDrill=>"独角钻",MoveId::Tackle=>"撞击",MoveId::BodySlam=>"泰山压顶",
            MoveId::Wrap=>"紧束",MoveId::TakeDown=>"猛撞",MoveId::Thrash=>"大闹一番",
            MoveId::DoubleEdge=>"舍身冲撞",MoveId::TailWhip=>"摇尾巴",MoveId::PoisonSting=>"毒针",
            MoveId::Twineedle=>"双针",MoveId::PinMissile=>"飞弹针",MoveId::Leer=>"瞪眼",
            MoveId::Bite=>"咬住",MoveId::Growl=>"叫声",MoveId::Roar=>"吼叫",MoveId::Sing=>"唱歌",
            MoveId::Supersonic=>"超音波",MoveId::Sonicboom=>"音爆",MoveId::Disable=>"定身法",
            MoveId::Acid=>"溶解液",MoveId::Ember=>"火花",MoveId::Flamethrower=>"喷射火焰",
            MoveId::Mist=>"白雾",MoveId::WaterGun=>"水枪",MoveId::HydroPump=>"水炮",
            MoveId::Surf=>"冲浪",MoveId::IceBeam=>"冰冻光束",MoveId::Blizzard=>"暴风雪",
            MoveId::Psybeam=>"幻象光线",MoveId::Bubblebeam=>"泡沫光线",MoveId::AuroraBeam=>"极光束",
            MoveId::HyperBeam=>"破坏光线",MoveId::Peck=>"啄",MoveId::DrillPeck=>"啄钻",
            MoveId::Submission=>"地狱翻滚",MoveId::LowKick=>"踢倒",MoveId::Counter=>"双倍奉还",
            MoveId::SeismicToss=>"地球上投",MoveId::Strength=>"怪力",MoveId::Absorb=>"吸取",
            MoveId::MegaDrain=>"超级吸取",MoveId::LeechSeed=>"寄生种子",MoveId::Growth=>"生长",
            MoveId::RazorLeaf=>"飞叶快刀",MoveId::Solarbeam=>"日光束",MoveId::Poisonpowder=>"毒粉",
            MoveId::StunSpore=>"麻痹粉",MoveId::SleepPowder=>"催眠粉",MoveId::PetalDance=>"花瓣舞",
            MoveId::StringShot=>"吐丝",MoveId::DragonRage=>"龙之怒",MoveId::FireSpin=>"火焰旋涡",
            MoveId::Thundershock=>"电击",MoveId::Thunderbolt=>"十万伏特",MoveId::ThunderWave=>"电磁波",
            MoveId::Thunder=>"打雷",MoveId::RockThrow=>"落石",MoveId::Earthquake=>"地震",
            MoveId::Fissure=>"地裂",MoveId::Dig=>"挖洞",MoveId::Toxic=>"剧毒",
            MoveId::Confusion=>"念力",MoveId::PsychicM=>"精神强念",MoveId::Hypnosis=>"催眠术",
            MoveId::Meditate=>"瑜伽姿势",MoveId::Agility=>"高速移动",MoveId::QuickAttack=>"电光一闪",
            MoveId::Rage=>"愤怒",MoveId::Teleport=>"瞬间移动",MoveId::NightShade=>"黑夜魔影",
            MoveId::Mimic=>"模仿",MoveId::Screech=>"刺耳声",MoveId::DoubleTeam=>"影子分身",
            MoveId::Recover=>"自我再生",MoveId::Harden=>"变硬",MoveId::Minimize=>"变小",
            MoveId::Smokescreen=>"烟幕",MoveId::ConfuseRay=>"奇异之光",MoveId::Withdraw=>"缩入壳中",
            MoveId::DefenseCurl=>"变圆",MoveId::Barrier=>"屏障",MoveId::LightScreen=>"光墙",
            MoveId::Haze=>"黑雾",MoveId::Reflect=>"反射壁",MoveId::FocusEnergy=>"聚气",
            MoveId::Bide=>"忍耐",MoveId::Metronome=>"挥指",MoveId::MirrorMove=>"鹦鹉学舌",
            MoveId::Selfdestruct=>"自爆",MoveId::EggBomb=>"炸蛋",MoveId::Lick=>"舌舔",
            MoveId::Smog=>"浊雾",MoveId::Sludge=>"污泥攻击",MoveId::BoneClub=>"骨棒",
            MoveId::FireBlast=>"大字爆炎",MoveId::Waterfall=>"攀瀑",MoveId::Clamp=>"贝壳夹击",
            MoveId::Swift=>"高速星星",MoveId::SkullBash=>"火箭头锤",MoveId::SpikeCannon=>"尖刺加农炮",
            MoveId::Constrict=>"缠绕",MoveId::Amnesia=>"瞬间失忆",MoveId::Kinesis=>"折弯汤匙",
            MoveId::Softboiled=>"生蛋",MoveId::HiJumpKick=>"飞膝踢",MoveId::Glare=>"大蛇瞪眼",
            MoveId::DreamEater=>"食梦",MoveId::PoisonGas=>"毒瓦斯",MoveId::Barrage=>"投球",
            MoveId::LeechLife=>"吸血",MoveId::LovelyKiss=>"恶魔之吻",MoveId::SkyAttack=>"神鸟猛击",
            MoveId::Transform=>"变身",MoveId::Bubble=>"泡沫",MoveId::DizzyPunch=>"迷昏拳",
            MoveId::Spore=>"蘑菇孢子",MoveId::Flash=>"闪光",MoveId::Psywave=>"精神波",
            MoveId::Splash=>"水溅跃",MoveId::AcidArmor=>"溶化",MoveId::Crabhammer=>"蟹钳锤",
            MoveId::Explosion=>"大爆炸",MoveId::FurySwipes=>"乱抓",MoveId::Bonemerang=>"骨头回力镖",
            MoveId::Rest=>"睡觉",MoveId::RockSlide=>"岩崩",MoveId::HyperFang=>"必杀门牙",
            MoveId::Sharpen=>"棱角化",MoveId::Conversion=>"纹理",MoveId::TriAttack=>"三重攻击",
            MoveId::SuperFang=>"愤怒门牙",MoveId::Slash=>"劈开",MoveId::Substitute=>"替身",
            MoveId::Struggle=>"挣扎",
            _ => "(move)",
        }
    } else {
        match m {
            MoveId::None=>"---",MoveId::Pound=>"POUND",MoveId::KarateChop=>"KARATE CHOP",
            MoveId::Doubleslap=>"DOUBLESLAP",MoveId::CometPunch=>"COMET PUNCH",MoveId::MegaPunch=>"MEGA PUNCH",
            MoveId::PayDay=>"PAY DAY",MoveId::FirePunch=>"FIRE PUNCH",MoveId::IcePunch=>"ICE PUNCH",
            MoveId::Thunderpunch=>"THUNDERPUNCH",MoveId::Scratch=>"SCRATCH",MoveId::Vicegrip=>"VICEGRIP",
            MoveId::Guillotine=>"GUILLOTINE",MoveId::RazorWind=>"RAZOR WIND",MoveId::SwordsDance=>"SWORDS DANCE",
            MoveId::Cut=>"CUT",MoveId::Gust=>"GUST",MoveId::WingAttack=>"WING ATTACK",
            MoveId::Whirlwind=>"WHIRLWIND",MoveId::Fly=>"FLY",MoveId::Bind=>"BIND",MoveId::Slam=>"SLAM",
            MoveId::VineWhip=>"VINE WHIP",MoveId::Stomp=>"STOMP",MoveId::DoubleKick=>"DOUBLE KICK",
            MoveId::MegaKick=>"MEGA KICK",MoveId::JumpKick=>"JUMP KICK",MoveId::RollingKick=>"ROLLING KICK",
            MoveId::SandAttack=>"SAND-ATTACK",MoveId::Headbutt=>"HEADBUTT",MoveId::HornAttack=>"HORN ATTACK",
            MoveId::FuryAttack=>"FURY ATTACK",MoveId::HornDrill=>"HORN DRILL",MoveId::Tackle=>"TACKLE",
            MoveId::BodySlam=>"BODY SLAM",MoveId::Wrap=>"WRAP",MoveId::TakeDown=>"TAKE DOWN",
            MoveId::Thrash=>"THRASH",MoveId::DoubleEdge=>"DOUBLE-EDGE",MoveId::TailWhip=>"TAIL WHIP",
            MoveId::PoisonSting=>"POISON STING",MoveId::Twineedle=>"TWINEEDLE",MoveId::PinMissile=>"PIN MISSILE",
            MoveId::Leer=>"LEER",MoveId::Bite=>"BITE",MoveId::Growl=>"GROWL",MoveId::Roar=>"ROAR",
            MoveId::Sing=>"SING",MoveId::Supersonic=>"SUPERSONIC",MoveId::Sonicboom=>"SONICBOOM",
            MoveId::Disable=>"DISABLE",MoveId::Acid=>"ACID",MoveId::Ember=>"EMBER",
            MoveId::Flamethrower=>"FLAMETHROWER",MoveId::Mist=>"MIST",MoveId::WaterGun=>"WATER GUN",
            MoveId::HydroPump=>"HYDRO PUMP",MoveId::Surf=>"SURF",MoveId::IceBeam=>"ICE BEAM",
            MoveId::Blizzard=>"BLIZZARD",MoveId::Psybeam=>"PSYBEAM",MoveId::Bubblebeam=>"BUBBLEBEAM",
            MoveId::AuroraBeam=>"AURORA BEAM",MoveId::HyperBeam=>"HYPER BEAM",MoveId::Peck=>"PECK",
            MoveId::DrillPeck=>"DRILL PECK",MoveId::Submission=>"SUBMISSION",MoveId::LowKick=>"LOW KICK",
            MoveId::Counter=>"COUNTER",MoveId::SeismicToss=>"SEISMIC TOSS",MoveId::Strength=>"STRENGTH",
            MoveId::Absorb=>"ABSORB",MoveId::MegaDrain=>"MEGA DRAIN",MoveId::LeechSeed=>"LEECH SEED",
            MoveId::Growth=>"GROWTH",MoveId::RazorLeaf=>"RAZOR LEAF",MoveId::Solarbeam=>"SOLARBEAM",
            MoveId::Poisonpowder=>"POISONPOWDER",MoveId::StunSpore=>"STUN SPORE",MoveId::SleepPowder=>"SLEEP POWDER",
            MoveId::PetalDance=>"PETAL DANCE",MoveId::StringShot=>"STRING SHOT",MoveId::DragonRage=>"DRAGON RAGE",
            MoveId::FireSpin=>"FIRE SPIN",MoveId::Thundershock=>"THUNDERSHOCK",MoveId::Thunderbolt=>"THUNDERBOLT",
            MoveId::ThunderWave=>"THUNDER WAVE",MoveId::Thunder=>"THUNDER",MoveId::RockThrow=>"ROCK THROW",
            MoveId::Earthquake=>"EARTHQUAKE",MoveId::Fissure=>"FISSURE",MoveId::Dig=>"DIG",
            MoveId::Toxic=>"TOXIC",MoveId::Confusion=>"CONFUSION",MoveId::PsychicM=>"PSYCHIC",
            MoveId::Hypnosis=>"HYPNOSIS",MoveId::Meditate=>"MEDITATE",MoveId::Agility=>"AGILITY",
            MoveId::QuickAttack=>"QUICK ATTACK",MoveId::Rage=>"RAGE",MoveId::Teleport=>"TELEPORT",
            MoveId::NightShade=>"NIGHT SHADE",MoveId::Mimic=>"MIMIC",MoveId::Screech=>"SCREECH",
            MoveId::DoubleTeam=>"DOUBLE TEAM",MoveId::Recover=>"RECOVER",MoveId::Harden=>"HARDEN",
            MoveId::Minimize=>"MINIMIZE",MoveId::Smokescreen=>"SMOKESCREEN",MoveId::ConfuseRay=>"CONFUSE RAY",
            MoveId::Withdraw=>"WITHDRAW",MoveId::DefenseCurl=>"DEFENSE CURL",MoveId::Barrier=>"BARRIER",
            MoveId::LightScreen=>"LIGHT SCREEN",MoveId::Haze=>"HAZE",MoveId::Reflect=>"REFLECT",
            MoveId::FocusEnergy=>"FOCUS ENERGY",MoveId::Bide=>"BIDE",MoveId::Metronome=>"METRONOME",
            MoveId::MirrorMove=>"MIRROR MOVE",MoveId::Selfdestruct=>"SELFDESTRUCT",MoveId::EggBomb=>"EGG BOMB",
            MoveId::Lick=>"LICK",MoveId::Smog=>"SMOG",MoveId::Sludge=>"SLUDGE",MoveId::BoneClub=>"BONE CLUB",
            MoveId::FireBlast=>"FIRE BLAST",MoveId::Waterfall=>"WATERFALL",MoveId::Clamp=>"CLAMP",
            MoveId::Swift=>"SWIFT",MoveId::SkullBash=>"SKULL BASH",MoveId::SpikeCannon=>"SPIKE CANNON",
            MoveId::Constrict=>"CONSTRICT",MoveId::Amnesia=>"AMNESIA",MoveId::Kinesis=>"KINESIS",
            MoveId::Softboiled=>"SOFTBOILED",MoveId::HiJumpKick=>"HI JUMP KICK",MoveId::Glare=>"GLARE",
            MoveId::DreamEater=>"DREAM EATER",MoveId::PoisonGas=>"POISON GAS",MoveId::Barrage=>"BARRAGE",
            MoveId::LeechLife=>"LEECH LIFE",MoveId::LovelyKiss=>"LOVELY KISS",MoveId::SkyAttack=>"SKY ATTACK",
            MoveId::Transform=>"TRANSFORM",MoveId::Bubble=>"BUBBLE",MoveId::DizzyPunch=>"DIZZY PUNCH",
            MoveId::Spore=>"SPORE",MoveId::Flash=>"FLASH",MoveId::Psywave=>"PSYWAVE",
            MoveId::Splash=>"SPLASH",MoveId::AcidArmor=>"ACID ARMOR",MoveId::Crabhammer=>"CRABHAMMER",
            MoveId::Explosion=>"EXPLOSION",MoveId::FurySwipes=>"FURY SWIPES",MoveId::Bonemerang=>"BONEMERANG",
            MoveId::Rest=>"REST",MoveId::RockSlide=>"ROCK SLIDE",MoveId::HyperFang=>"HYPER FANG",
            MoveId::Sharpen=>"SHARPEN",MoveId::Conversion=>"CONVERSION",MoveId::TriAttack=>"TRI ATTACK",
            MoveId::SuperFang=>"SUPER FANG",MoveId::Slash=>"SLASH",MoveId::Substitute=>"SUBSTITUTE",
            MoveId::Struggle=>"STRUGGLE",
            _ => "---",
        }
    }
}

pub fn item_name(id: crate::items::ItemId, is_zh: bool) -> &'static str {
    if is_zh {
        match id {
            crate::items::ItemId::NoItem => "---",
            crate::items::ItemId::MasterBall => "大师球",
            crate::items::ItemId::UltraBall => "高级球",
            crate::items::ItemId::GreatBall => "超级球",
            crate::items::ItemId::PokeBall => "精灵球",
            crate::items::ItemId::TownMap => "城镇地图",
            crate::items::ItemId::Bicycle => "自行车",
            crate::items::ItemId::Surfboard => "？？？？？",
            crate::items::ItemId::SafariBall => "狩猎球",
            crate::items::ItemId::Pokedex => "宝可梦图鉴",
            crate::items::ItemId::MoonStone => "月之石",
            crate::items::ItemId::Antidote => "解毒药",
            crate::items::ItemId::BurnHeal => "灼伤药",
            crate::items::ItemId::IceHeal => "解冻药",
            crate::items::ItemId::Awakening => "清醒药",
            crate::items::ItemId::ParlyzHeal => "麻痹药",
            crate::items::ItemId::FullRestore => "全复药",
            crate::items::ItemId::MaxPotion => "全满药",
            crate::items::ItemId::HyperPotion => "厉害伤药",
            crate::items::ItemId::SuperPotion => "好伤药",
            crate::items::ItemId::Potion => "伤药",
            crate::items::ItemId::BoulderBadge => "灰色徽章",
            crate::items::ItemId::CascadeBadge => "蓝色徽章",
            crate::items::ItemId::ThunderBadge => "橙色徽章",
            crate::items::ItemId::RainbowBadge => "彩虹徽章",
            crate::items::ItemId::SoulBadge => "灵魂徽章",
            crate::items::ItemId::MarshBadge => "粉色徽章",
            crate::items::ItemId::VolcanoBadge => "深红徽章",
            crate::items::ItemId::EarthBadge => "绿色徽章",
            crate::items::ItemId::EscapeRope => "逃脱绳",
            crate::items::ItemId::Repel => "驱虫剂",
            crate::items::ItemId::OldAmber => "秘密琥珀",
            crate::items::ItemId::FireStone => "火之石",
            crate::items::ItemId::ThunderStone => "雷之石",
            crate::items::ItemId::WaterStone => "水之石",
            crate::items::ItemId::HpUp => "体力增强剂",
            crate::items::ItemId::Protein => "攻击增强剂",
            crate::items::ItemId::Iron => "防御增强剂",
            crate::items::ItemId::Carbos => "速度增强剂",
            crate::items::ItemId::Calcium => "特攻增强剂",
            crate::items::ItemId::RareCandy => "神奇糖果",
            crate::items::ItemId::DomeFossil => "甲壳化石",
            crate::items::ItemId::HelixFossil => "贝壳化石",
            crate::items::ItemId::SecretKey => "秘密钥匙",
            crate::items::ItemId::Unused2C => "？？？？？",
            crate::items::ItemId::BikeVoucher => "自行车兑换券",
            crate::items::ItemId::XAccuracy => "特攻强化",
            crate::items::ItemId::LeafStone => "叶之石",
            crate::items::ItemId::CardKey => "磁卡钥匙",
            crate::items::ItemId::Nugget => "金珠",
            crate::items::ItemId::Unused32 => "？？？？？",
            crate::items::ItemId::PokeDoll => "皮皮玩偶",
            crate::items::ItemId::FullHeal => "万灵药",
            crate::items::ItemId::Revive => "活力碎片",
            crate::items::ItemId::MaxRevive => "活力块",
            crate::items::ItemId::GuardSpec => "特殊防御",
            crate::items::ItemId::SuperRepel => "好驱虫剂",
            crate::items::ItemId::MaxRepel => "厉害驱虫剂",
            crate::items::ItemId::DireHit => "会心药片",
            crate::items::ItemId::Coin => "代币",
            crate::items::ItemId::FreshWater => "新鲜水",
            crate::items::ItemId::SodaPop => "汽水",
            crate::items::ItemId::Lemonade => "柠檬水",
            crate::items::ItemId::SsTicket => "圣安奴号船票",
            crate::items::ItemId::GoldTeeth => "金假牙",
            crate::items::ItemId::XAttack => "力量强化",
            crate::items::ItemId::XDefend => "防御强化",
            crate::items::ItemId::XSpeed => "速度强化",
            crate::items::ItemId::XSpecial => "特防强化",
            crate::items::ItemId::CoinCase => "代币盒",
            crate::items::ItemId::OaksParcel => "大木博士的包裹",
            crate::items::ItemId::Itemfinder => "探宝器",
            crate::items::ItemId::SilphScope => "西尔佛透视镜",
            crate::items::ItemId::PokeFlute => "宝可梦之笛",
            crate::items::ItemId::LiftKey => "电梯钥匙",
            crate::items::ItemId::ExpAll => "学习装置",
            crate::items::ItemId::OldRod => "破旧钓竿",
            crate::items::ItemId::GoodRod => "好钓竿",
            crate::items::ItemId::SuperRod => "厉害钓竿",
            crate::items::ItemId::PpUp => "PP提升剂",
            crate::items::ItemId::Ether => "元气药片",
            crate::items::ItemId::MaxEther => "元气药块",
            crate::items::ItemId::Elixer => "招式补药",
            crate::items::ItemId::MaxElixer => "招式全补药",
            _ => "(item)",
        }
    } else {
        crate::item_data::get_item_data(id).map(|d| d.name).unwrap_or("---")
    }
}

pub fn ui_label<'a>(key: &'a str, is_zh: bool) -> &'a str {
    if !is_zh { return key; }
    match key {
        "POKéDEX" => "宝可梦图鉴",
        "POKéMON" => "宝可梦",
        "ITEM" => "道具",
        "NEW GAME" => "新游戏",
        "OPTION" => "选项",
        "CONTINUE" => "继续游戏",
        "FIGHT" => "战斗",
        "PKMN" => "宝可梦",
        "RUN" => "逃跑",
        "PLAYER" => "玩家",
        "BADGES" => "徽章",
        "#DEX" => "图鉴",
        "TIME" => "时间",
        "Now saving..." => "正在保存……",
        "the game!" => "游戏中！",
        "Would you like to" => "是否要",
        "SAVE the game?" => "保存游戏？",
        "YES" => "是",
        "NO" => "否",
        "TEXT SPEED" => "文字速度",
        " FAST  MEDIUM SLOW" => " 快  中  慢",
        "BATTLE ANIMATION" => "战斗动画",
        " ON       OFF" => " 开       关",
        "BATTLE STYLE" => "战斗模式",
        " SHIFT    SET" => " 替换    固定",
        "CANCEL" => "取消",
        "EXIT" => "退出",
        "RESET" => "重置",
        "SEEN" => "已见",
        "OWN" => "拥有",
        "NAME/" => "名字",
        "MONEY/" => "金钱",
        "TIME/" => "时间",
        "BADGES" => "徽章",
        "HP:" => "HP：",
        "STATUS/" => "状态/",
        "TYPE1/" => "属性1/",
        "TYPE2/" => "属性2/",
        "ID №/" => "编号/",
        "OT/" => "主人/",
        "EXP POINTS" => "经验值",
        "LEVEL UP" => "升级",
        "to" => "至",
        "BUY" => "购买",
        "SELL" => "出售",
        "USE" => "使用",
        "TOSS" => "扔掉",
        "QUIT" => "退出",
        "DATA" => "数据",
        "CRY" => "叫声",
        "AREA" => "区域",
        "AREA UNKNOWN" => "区域未知",
        "'s NEST" => "的巢穴",
        "EXIT" => "退出",
        "SAVE" => "保存",
        "HT" => "身高",
        "WT" => "体重",
        "B:Cancel" => "B：取消",
        "No #MON!" => "无宝可梦！",
        // PC storage / Bill's PC labels.
        "WITHDRAW" => "取出",
        "DEPOSIT" => "存放",
        "RELEASE" => "放生",
        "CHANGE BOX" => "更换盒子",
        "SEE YA!" => "再见！",
        "LOG OFF" => "退出登录",
        "STATS" => "状态",
        "WITHDRAW #MON" => "取出宝可梦",
        "DEPOSIT #MON" => "存放宝可梦",
        "RELEASE #MON" => "放生宝可梦",
        "WITHDRAW ITEM" => "取出道具",
        "DEPOSIT ITEM" => "存放道具",
        "TOSS ITEM" => "扔掉道具",
        "LEVEL/" => "等级/",
        "HALL OF FAME" => "名人堂",
        "PLAY TIME" => "游戏时间",
        "MONEY" => "金钱",
        // Game Corner slots.
        "SLOT MACHINE" => "老虎机",
        "COINS" => "代币",
        "BET" => "下注",
        // Elevator / item-filter prompts.
        "WHICH FLOOR?" => "要去几楼？",
        "WHICH ONE?" => "选哪个？",
        "A SELECT" => "A：选择",
        "B BACK" => "B：返回",
        "Diploma" => "文凭",
        _ => key,
    }
}
