//! Move → sound-effect table: a transcription of `MoveSoundTable` from the
//! original game's `data/moves/sfx.asm`, plus a port of the `GetMoveSound` /
//! `IsCryMove` routines from `engine/battle/animations.asm`.
//!
//! Each row is `(sfx id, pitch mod, tempo mod)`. In the original ROM the sfx
//! id indexes the audio banks' header tables; here the id is in the
//! `pokered_audio::sfx_data::SfxId` id space (header-entry order, as
//! generated by `tools/asm2sfx.py`). `pitch_mod`/`tempo_mod` are the
//! ROM-verbatim `wFrequencyModifier`/`wTempoModifier` bytes; the audio
//! engine currently does not apply them (see docs/FIDELITY_GAPS.md).
//!
//! Verified byte-for-byte (pitch/tempo) and id-for-id (sfx) against the
//! disassembly by `scripts/verify_move_sfx_data.py`.

use crate::moves::MoveId;
use crate::species::Species;

/// One `MoveSoundTable` row: `db SFX_*, pitch_mod, tempo_mod`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MoveSfx {
    /// Base SFX id (`SfxId` id space).
    pub sfx: u8,
    /// `wFrequencyModifier` addend (unapplied — see module docs).
    pub pitch_mod: u8,
    /// `wTempoModifier` addend (unapplied — see module docs).
    pub tempo_mod: u8,
}

/// The sound a move-animation command plays, per `GetMoveSound`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveSound {
    /// Play this SFX id (`SfxId` id space).
    Sfx(u8),
    /// `IsCryMove` (GROWL/ROAR): play the whose-turn mon's cry instead
    /// (`GetCryData` on `wBattleMonSpecies`/`wEnemyMonSpecies`). The
    /// command's MoveSoundTable row bytes are ADDED to the cry's own
    /// pitch/length modifiers (the `add [hl]` in `GetMoveSound`).
    Cry {
        species: Species,
        pitch_mod: u8,
        tempo_mod: u8,
    },
}

/// `MoveSoundTable`: NUM_ATTACKS rows (index = move id - 1) plus the one
/// trailing row the original table carries after
/// `assert_table_length NUM_ATTACKS` (unreachable via a valid move id).
pub static MOVE_SFX_TABLE: [MoveSfx; 166] = [
    MoveSfx { sfx: 105, pitch_mod: 0x00, tempo_mod: 0x80 }, // POUND
    MoveSfx { sfx: 107, pitch_mod: 0x10, tempo_mod: 0x80 }, // KARATE_CHOP
    MoveSfx { sfx: 124, pitch_mod: 0x00, tempo_mod: 0x80 }, // DOUBLESLAP
    MoveSfx { sfx: 106, pitch_mod: 0x01, tempo_mod: 0x80 }, // COMET_PUNCH
    MoveSfx { sfx: 108, pitch_mod: 0x00, tempo_mod: 0x40 }, // MEGA_PUNCH
    MoveSfx { sfx: 150, pitch_mod: 0x00, tempo_mod: 0xFF }, // PAY_DAY
    MoveSfx { sfx: 108, pitch_mod: 0x10, tempo_mod: 0x60 }, // FIRE_PUNCH
    MoveSfx { sfx: 108, pitch_mod: 0x20, tempo_mod: 0x80 }, // ICE_PUNCH
    MoveSfx { sfx: 108, pitch_mod: 0x00, tempo_mod: 0xA0 }, // THUNDERPUNCH
    MoveSfx { sfx: 111, pitch_mod: 0x00, tempo_mod: 0x80 }, // SCRATCH
    MoveSfx { sfx: 110, pitch_mod: 0x20, tempo_mod: 0x40 }, // VICEGRIP
    MoveSfx { sfx: 110, pitch_mod: 0x00, tempo_mod: 0x80 }, // GUILLOTINE
    MoveSfx { sfx: 109, pitch_mod: 0x00, tempo_mod: 0xA0 }, // RAZOR_WIND
    MoveSfx { sfx: 112, pitch_mod: 0x10, tempo_mod: 0xC0 }, // SWORDS_DANCE
    MoveSfx { sfx: 112, pitch_mod: 0x00, tempo_mod: 0xA0 }, // CUT
    MoveSfx { sfx: 113, pitch_mod: 0x00, tempo_mod: 0xC0 }, // GUST
    MoveSfx { sfx: 113, pitch_mod: 0x10, tempo_mod: 0xA0 }, // WING_ATTACK
    MoveSfx { sfx: 114, pitch_mod: 0x00, tempo_mod: 0xE0 }, // WHIRLWIND
    MoveSfx { sfx: 112, pitch_mod: 0x20, tempo_mod: 0xC0 }, // FLY
    MoveSfx { sfx: 115, pitch_mod: 0x00, tempo_mod: 0x80 }, // BIND
    MoveSfx { sfx: 129, pitch_mod: 0x00, tempo_mod: 0x80 }, // SLAM
    MoveSfx { sfx: 116, pitch_mod: 0x01, tempo_mod: 0x80 }, // VINE_WHIP
    MoveSfx { sfx: 127, pitch_mod: 0x00, tempo_mod: 0x80 }, // STOMP
    MoveSfx { sfx: 118, pitch_mod: 0xF0, tempo_mod: 0x40 }, // DOUBLE_KICK
    MoveSfx { sfx: 121, pitch_mod: 0x00, tempo_mod: 0x80 }, // MEGA_KICK
    MoveSfx { sfx: 118, pitch_mod: 0x00, tempo_mod: 0x80 }, // JUMP_KICK
    MoveSfx { sfx: 128, pitch_mod: 0x10, tempo_mod: 0x80 }, // ROLLING_KICK
    MoveSfx { sfx: 122, pitch_mod: 0x01, tempo_mod: 0xA0 }, // SAND_ATTACK
    MoveSfx { sfx: 119, pitch_mod: 0x00, tempo_mod: 0x80 }, // HEADBUTT
    MoveSfx { sfx: 125, pitch_mod: 0x00, tempo_mod: 0x60 }, // HORN_ATTACK
    MoveSfx { sfx: 125, pitch_mod: 0x01, tempo_mod: 0x40 }, // FURY_ATTACK
    MoveSfx { sfx: 126, pitch_mod: 0x00, tempo_mod: 0xA0 }, // HORN_DRILL
    MoveSfx { sfx: 121, pitch_mod: 0x10, tempo_mod: 0xA0 }, // TACKLE
    MoveSfx { sfx: 127, pitch_mod: 0x00, tempo_mod: 0xC0 }, // BODY_SLAM
    MoveSfx { sfx: 115, pitch_mod: 0x10, tempo_mod: 0x60 }, // WRAP
    MoveSfx { sfx: 121, pitch_mod: 0x00, tempo_mod: 0xA0 }, // TAKE_DOWN
    MoveSfx { sfx: 129, pitch_mod: 0x11, tempo_mod: 0xC0 }, // THRASH
    MoveSfx { sfx: 121, pitch_mod: 0x20, tempo_mod: 0xC0 }, // DOUBLE_EDGE
    MoveSfx { sfx: 128, pitch_mod: 0x00, tempo_mod: 0x80 }, // TAIL_WHIP
    MoveSfx { sfx: 122, pitch_mod: 0x00, tempo_mod: 0x80 }, // POISON_STING
    MoveSfx { sfx: 122, pitch_mod: 0x20, tempo_mod: 0xC0 }, // TWINEEDLE
    MoveSfx { sfx: 120, pitch_mod: 0x00, tempo_mod: 0x80 }, // PIN_MISSILE
    MoveSfx { sfx: 144, pitch_mod: 0xFF, tempo_mod: 0x40 }, // LEER
    MoveSfx { sfx: 125, pitch_mod: 0x00, tempo_mod: 0x80 }, // BITE
    MoveSfx { sfx: 106, pitch_mod: 0x00, tempo_mod: 0xC0 }, // GROWL
    MoveSfx { sfx: 106, pitch_mod: 0x00, tempo_mod: 0x40 }, // ROAR
    MoveSfx { sfx: 148, pitch_mod: 0x00, tempo_mod: 0x80 }, // SING
    MoveSfx { sfx: 134, pitch_mod: 0x40, tempo_mod: 0x60 }, // SUPERSONIC
    MoveSfx { sfx: 134, pitch_mod: 0x00, tempo_mod: 0x80 }, // SONICBOOM
    MoveSfx { sfx: 134, pitch_mod: 0xFF, tempo_mod: 0x40 }, // DISABLE
    MoveSfx { sfx: 137, pitch_mod: 0x80, tempo_mod: 0xC0 }, // ACID
    MoveSfx { sfx: 120, pitch_mod: 0x10, tempo_mod: 0xA0 }, // EMBER
    MoveSfx { sfx: 120, pitch_mod: 0x21, tempo_mod: 0xE0 }, // FLAMETHROWER
    MoveSfx { sfx: 136, pitch_mod: 0x00, tempo_mod: 0x80 }, // MIST
    MoveSfx { sfx: 131, pitch_mod: 0x20, tempo_mod: 0x60 }, // WATER_GUN
    MoveSfx { sfx: 137, pitch_mod: 0x00, tempo_mod: 0x80 }, // HYDRO_PUMP
    MoveSfx { sfx: 139, pitch_mod: 0x00, tempo_mod: 0x80 }, // SURF
    MoveSfx { sfx: 135, pitch_mod: 0x40, tempo_mod: 0x80 }, // ICE_BEAM
    MoveSfx { sfx: 136, pitch_mod: 0xF0, tempo_mod: 0xE0 }, // BLIZZARD
    MoveSfx { sfx: 140, pitch_mod: 0x00, tempo_mod: 0x80 }, // PSYBEAM
    MoveSfx { sfx: 137, pitch_mod: 0xF0, tempo_mod: 0x60 }, // BUBBLEBEAM
    MoveSfx { sfx: 135, pitch_mod: 0x00, tempo_mod: 0x80 }, // AURORA_BEAM
    MoveSfx { sfx: 149, pitch_mod: 0x00, tempo_mod: 0x80 }, // HYPER_BEAM
    MoveSfx { sfx: 102, pitch_mod: 0x01, tempo_mod: 0xA0 }, // PECK
    MoveSfx { sfx: 114, pitch_mod: 0xF0, tempo_mod: 0x20 }, // DRILL_PECK
    MoveSfx { sfx: 130, pitch_mod: 0x01, tempo_mod: 0xC0 }, // SUBMISSION
    MoveSfx { sfx: 130, pitch_mod: 0x00, tempo_mod: 0x80 }, // LOW_KICK
    MoveSfx { sfx: 121, pitch_mod: 0x00, tempo_mod: 0xE0 }, // COUNTER
    MoveSfx { sfx: 133, pitch_mod: 0x01, tempo_mod: 0x60 }, // SEISMIC_TOSS
    MoveSfx { sfx: 133, pitch_mod: 0x20, tempo_mod: 0x40 }, // STRENGTH
    MoveSfx { sfx: 131, pitch_mod: 0x00, tempo_mod: 0x80 }, // ABSORB
    MoveSfx { sfx: 131, pitch_mod: 0x40, tempo_mod: 0xC0 }, // MEGA_DRAIN
    MoveSfx { sfx: 122, pitch_mod: 0x03, tempo_mod: 0x60 }, // LEECH_SEED
    MoveSfx { sfx: 132, pitch_mod: 0x11, tempo_mod: 0xE0 }, // GROWTH
    MoveSfx { sfx: 113, pitch_mod: 0x20, tempo_mod: 0xE0 }, // RAZOR_LEAF
    MoveSfx { sfx: 141, pitch_mod: 0x00, tempo_mod: 0x80 }, // SOLARBEAM
    MoveSfx { sfx: 123, pitch_mod: 0x00, tempo_mod: 0x80 }, // POISONPOWDER
    MoveSfx { sfx: 123, pitch_mod: 0x11, tempo_mod: 0xA0 }, // STUN_SPORE
    MoveSfx { sfx: 123, pitch_mod: 0x01, tempo_mod: 0xC0 }, // SLEEP_POWDER
    MoveSfx { sfx: 114, pitch_mod: 0x14, tempo_mod: 0xC0 }, // PETAL_DANCE
    MoveSfx { sfx: 122, pitch_mod: 0x02, tempo_mod: 0xA0 }, // STRING_SHOT
    MoveSfx { sfx: 136, pitch_mod: 0xF0, tempo_mod: 0x80 }, // DRAGON_RAGE
    MoveSfx { sfx: 136, pitch_mod: 0x20, tempo_mod: 0xC0 }, // FIRE_SPIN
    MoveSfx { sfx: 142, pitch_mod: 0x00, tempo_mod: 0x20 }, // THUNDERSHOCK
    MoveSfx { sfx: 142, pitch_mod: 0x20, tempo_mod: 0x80 }, // THUNDERBOLT
    MoveSfx { sfx: 141, pitch_mod: 0x12, tempo_mod: 0x60 }, // THUNDER_WAVE
    MoveSfx { sfx: 133, pitch_mod: 0x00, tempo_mod: 0x80 }, // THUNDER
    MoveSfx { sfx: 115, pitch_mod: 0x01, tempo_mod: 0xE0 }, // ROCK_THROW
    MoveSfx { sfx: 136, pitch_mod: 0x0F, tempo_mod: 0xE0 }, // EARTHQUAKE
    MoveSfx { sfx: 136, pitch_mod: 0x11, tempo_mod: 0x20 }, // FISSURE
    MoveSfx { sfx: 111, pitch_mod: 0x10, tempo_mod: 0x40 }, // DIG
    MoveSfx { sfx: 110, pitch_mod: 0x10, tempo_mod: 0xC0 }, // TOXIC
    MoveSfx { sfx: 115, pitch_mod: 0x00, tempo_mod: 0x20 }, // CONFUSION
    MoveSfx { sfx: 143, pitch_mod: 0x00, tempo_mod: 0x80 }, // PSYCHIC_M
    MoveSfx { sfx: 148, pitch_mod: 0x11, tempo_mod: 0x18 }, // HYPNOSIS
    MoveSfx { sfx: 104, pitch_mod: 0x20, tempo_mod: 0xC0 }, // MEDITATE
    MoveSfx { sfx: 103, pitch_mod: 0x20, tempo_mod: 0xC0 }, // AGILITY
    MoveSfx { sfx: 132, pitch_mod: 0x00, tempo_mod: 0x10 }, // QUICK_ATTACK
    MoveSfx { sfx: 133, pitch_mod: 0xF0, tempo_mod: 0x20 }, // RAGE
    MoveSfx { sfx: 146, pitch_mod: 0xF0, tempo_mod: 0xC0 }, // TELEPORT
    MoveSfx { sfx: 112, pitch_mod: 0xF0, tempo_mod: 0xE0 }, // NIGHT_SHADE
    MoveSfx { sfx: 104, pitch_mod: 0xF0, tempo_mod: 0x40 }, // MIMIC
    MoveSfx { sfx: 144, pitch_mod: 0x00, tempo_mod: 0x80 }, // SCREECH
    MoveSfx { sfx: 146, pitch_mod: 0x80, tempo_mod: 0x40 }, // DOUBLE_TEAM
    MoveSfx { sfx: 146, pitch_mod: 0x00, tempo_mod: 0x80 }, // RECOVER
    MoveSfx { sfx: 115, pitch_mod: 0x11, tempo_mod: 0x20 }, // HARDEN
    MoveSfx { sfx: 115, pitch_mod: 0x22, tempo_mod: 0x10 }, // MINIMIZE
    MoveSfx { sfx: 122, pitch_mod: 0xF1, tempo_mod: 0xFF }, // SMOKESCREEN
    MoveSfx { sfx: 114, pitch_mod: 0xF1, tempo_mod: 0xFF }, // CONFUSE_RAY
    MoveSfx { sfx: 115, pitch_mod: 0x33, tempo_mod: 0x30 }, // WITHDRAW
    MoveSfx { sfx: 145, pitch_mod: 0x40, tempo_mod: 0xC0 }, // DEFENSE_CURL
    MoveSfx { sfx: 109, pitch_mod: 0x20, tempo_mod: 0x20 }, // BARRIER
    MoveSfx { sfx: 109, pitch_mod: 0xF0, tempo_mod: 0x10 }, // LIGHT_SCREEN
    MoveSfx { sfx: 110, pitch_mod: 0xF8, tempo_mod: 0x10 }, // HAZE
    MoveSfx { sfx: 112, pitch_mod: 0xF0, tempo_mod: 0x10 }, // REFLECT
    MoveSfx { sfx: 132, pitch_mod: 0x00, tempo_mod: 0x80 }, // FOCUS_ENERGY
    MoveSfx { sfx: 119, pitch_mod: 0x00, tempo_mod: 0xC0 }, // BIDE
    MoveSfx { sfx: 145, pitch_mod: 0xC0, tempo_mod: 0xFF }, // METRONOME
    MoveSfx { sfx: 104, pitch_mod: 0xF2, tempo_mod: 0x20 }, // MIRROR_MOVE
    MoveSfx { sfx: 147, pitch_mod: 0x00, tempo_mod: 0x80 }, // SELFDESTRUCT
    MoveSfx { sfx: 147, pitch_mod: 0x00, tempo_mod: 0x40 }, // EGG_BOMB
    MoveSfx { sfx: 104, pitch_mod: 0x00, tempo_mod: 0x40 }, // LICK
    MoveSfx { sfx: 112, pitch_mod: 0x10, tempo_mod: 0xFF }, // SMOG
    MoveSfx { sfx: 137, pitch_mod: 0x20, tempo_mod: 0x20 }, // SLUDGE
    MoveSfx { sfx: 145, pitch_mod: 0x00, tempo_mod: 0x80 }, // BONE_CLUB
    MoveSfx { sfx: 136, pitch_mod: 0x1F, tempo_mod: 0x20 }, // FIRE_BLAST
    MoveSfx { sfx: 132, pitch_mod: 0x2F, tempo_mod: 0x80 }, // WATERFALL
    MoveSfx { sfx: 110, pitch_mod: 0x1F, tempo_mod: 0xFF }, // CLAMP
    MoveSfx { sfx: 138, pitch_mod: 0x1F, tempo_mod: 0x60 }, // SWIFT
    MoveSfx { sfx: 133, pitch_mod: 0x1E, tempo_mod: 0x20 }, // SKULL_BASH
    MoveSfx { sfx: 133, pitch_mod: 0x1F, tempo_mod: 0x18 }, // SPIKE_CANNON
    MoveSfx { sfx: 115, pitch_mod: 0x0F, tempo_mod: 0x80 }, // CONSTRICT
    MoveSfx { sfx: 104, pitch_mod: 0xF8, tempo_mod: 0x10 }, // AMNESIA
    MoveSfx { sfx: 103, pitch_mod: 0x18, tempo_mod: 0x20 }, // KINESIS
    MoveSfx { sfx: 145, pitch_mod: 0x08, tempo_mod: 0x40 }, // SOFTBOILED
    MoveSfx { sfx: 118, pitch_mod: 0x01, tempo_mod: 0xE0 }, // HI_JUMP_KICK
    MoveSfx { sfx: 112, pitch_mod: 0x09, tempo_mod: 0xFF }, // GLARE
    MoveSfx { sfx: 148, pitch_mod: 0x42, tempo_mod: 0x01 }, // DREAM_EATER
    MoveSfx { sfx: 123, pitch_mod: 0x00, tempo_mod: 0xFF }, // POISON_GAS
    MoveSfx { sfx: 145, pitch_mod: 0x08, tempo_mod: 0xE0 }, // BARRAGE
    MoveSfx { sfx: 131, pitch_mod: 0x00, tempo_mod: 0x80 }, // LEECH_LIFE
    MoveSfx { sfx: 104, pitch_mod: 0x88, tempo_mod: 0x10 }, // LOVELY_KISS
    MoveSfx { sfx: 132, pitch_mod: 0x48, tempo_mod: 0xFF }, // SKY_ATTACK
    MoveSfx { sfx: 103, pitch_mod: 0xFF, tempo_mod: 0xFF }, // TRANSFORM
    MoveSfx { sfx: 131, pitch_mod: 0xFF, tempo_mod: 0x10 }, // BUBBLE
    MoveSfx { sfx: 103, pitch_mod: 0xFF, tempo_mod: 0x04 }, // DIZZY_PUNCH
    MoveSfx { sfx: 123, pitch_mod: 0x01, tempo_mod: 0xFF }, // SPORE
    MoveSfx { sfx: 114, pitch_mod: 0xF8, tempo_mod: 0xFF }, // FLASH
    MoveSfx { sfx: 107, pitch_mod: 0xF0, tempo_mod: 0xF0 }, // PSYWAVE
    MoveSfx { sfx: 110, pitch_mod: 0x08, tempo_mod: 0x10 }, // SPLASH
    MoveSfx { sfx: 108, pitch_mod: 0xF0, tempo_mod: 0xFF }, // ACID_ARMOR
    MoveSfx { sfx: 121, pitch_mod: 0xF0, tempo_mod: 0xFF }, // CRABHAMMER
    MoveSfx { sfx: 147, pitch_mod: 0x10, tempo_mod: 0xFF }, // EXPLOSION
    MoveSfx { sfx: 109, pitch_mod: 0xF0, tempo_mod: 0x20 }, // FURY_SWIPES
    MoveSfx { sfx: 138, pitch_mod: 0xF0, tempo_mod: 0x60 }, // BONEMERANG
    MoveSfx { sfx: 128, pitch_mod: 0x12, tempo_mod: 0x10 }, // REST
    MoveSfx { sfx: 149, pitch_mod: 0xF0, tempo_mod: 0x20 }, // ROCK_SLIDE
    MoveSfx { sfx: 125, pitch_mod: 0x12, tempo_mod: 0xFF }, // HYPER_FANG
    MoveSfx { sfx: 144, pitch_mod: 0x80, tempo_mod: 0x04 }, // SHARPEN
    MoveSfx { sfx: 146, pitch_mod: 0xF0, tempo_mod: 0x10 }, // CONVERSION
    MoveSfx { sfx: 136, pitch_mod: 0xF8, tempo_mod: 0xFF }, // TRI_ATTACK
    MoveSfx { sfx: 133, pitch_mod: 0xF0, tempo_mod: 0xFF }, // SUPER_FANG
    MoveSfx { sfx: 112, pitch_mod: 0x01, tempo_mod: 0xFF }, // SLASH
    MoveSfx { sfx: 139, pitch_mod: 0xD8, tempo_mod: 0x04 }, // SUBSTITUTE
    MoveSfx { sfx: 106, pitch_mod: 0x00, tempo_mod: 0x80 }, // STRUGGLE
    MoveSfx { sfx: 106, pitch_mod: 0x00, tempo_mod: 0x80 }, // (table tail)
];

/// `GetMoveSound` (engine/battle/animations.asm): resolve the sound for an
/// animation command's sound byte.
///
/// * `anim_move` — `wAnimationID`: the move whose animation is playing.
/// * `sound_move` — the command's sound field: a move id, 0 = NO_MOVE
///   (the original stores NO_MOVE - 1 in the command stream and skips
///   playing anything).
/// * `attacker_species` — species of the whose-turn mon (`hWhoseTurn`).
///
/// Returns `None` when the command plays no sound. For GROWL/ROAR
/// (`IsCryMove`) every command sound becomes the attacker's cry, with the
/// command's table row bytes added to the cry's pitch/length modifiers
/// (`wFrequencyModifier`/`wTempoModifier`).
pub fn get_move_sound(
    anim_move: MoveId,
    sound_move: u8,
    attacker_species: Species,
) -> Option<MoveSound> {
    if sound_move == 0 {
        return None;
    }
    // IsCryMove: carry set when wAnimationID is GROWL or ROAR.
    if matches!(anim_move, MoveId::Growl | MoveId::Roar) {
        let entry = MOVE_SFX_TABLE.get(sound_move as usize - 1)?;
        return Some(MoveSound::Cry {
            species: attacker_species,
            pitch_mod: entry.pitch_mod,
            tempo_mod: entry.tempo_mod,
        });
    }
    // Table is indexed by the command-stream byte = move id - 1.
    let entry = MOVE_SFX_TABLE.get(sound_move as usize - 1)?;
    Some(MoveSound::Sfx(entry.sfx))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_length_matches_num_attacks_plus_tail() {
        // NUM_ATTACKS = 165 (STRUGGLE); +1 trailing row in the asm table.
        assert_eq!(MOVE_SFX_TABLE.len(), 166);
    }

    #[test]
    fn spot_check_entries() {
        // POUND: db SFX_POUND, $00, $80 (SfxId::Pound = 105).
        assert_eq!(
            MOVE_SFX_TABLE[MoveId::Pound as usize - 1],
            MoveSfx { sfx: 105, pitch_mod: 0x00, tempo_mod: 0x80 }
        );
        // STRUGGLE: db SFX_BATTLE_0B, $00, $80 (SfxId::Battle0B = 106).
        assert_eq!(
            MOVE_SFX_TABLE[MoveId::Struggle as usize - 1],
            MoveSfx { sfx: 106, pitch_mod: 0x00, tempo_mod: 0x80 }
        );
    }

    #[test]
    fn get_move_sound_table_lookup() {
        // TACKLE (0x21): SFX_SUPER_EFFECTIVE = 121.
        assert_eq!(
            get_move_sound(MoveId::Tackle, MoveId::Tackle as u8, Species::Rattata),
            Some(MoveSound::Sfx(121))
        );
        // NO_MOVE sound byte plays nothing.
        assert_eq!(get_move_sound(MoveId::Pound, 0, Species::Rattata), None);
    }

    #[test]
    fn get_move_sound_cry_moves() {
        // IsCryMove: GROWL/ROAR animations play the attacker's cry, even
        // for command sound bytes naming other moves; the command row's
        // pitch/tempo bytes are added to the cry's modifiers.
        let growl = &MOVE_SFX_TABLE[MoveId::Growl as usize - 1];
        assert_eq!(
            get_move_sound(MoveId::Growl, MoveId::Growl as u8, Species::Pikachu),
            Some(MoveSound::Cry {
                species: Species::Pikachu,
                pitch_mod: growl.pitch_mod,
                tempo_mod: growl.tempo_mod,
            })
        );
        let pound = &MOVE_SFX_TABLE[MoveId::Pound as usize - 1];
        assert_eq!(
            get_move_sound(MoveId::Roar, MoveId::Pound as u8, Species::Onix),
            Some(MoveSound::Cry {
                species: Species::Onix,
                pitch_mod: pound.pitch_mod,
                tempo_mod: pound.tempo_mod,
            })
        );
    }
}
