use num_derive::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use strum::EnumCount;
use strum_macros::{Display, EnumIter, EnumString};

// The `MoveId` enum is generated by `pokered-data/build.rs` from the
// `moves/*.json` filenames (see `generate_moves_enum`): `None = 0x00`, the
// canonical order keeps its byte IDs (0x01..=0xA5), and moves added through
// the editor are appended with IDs 0xA6+ (sorted by filename). The derive
// set is emitted fully-qualified into the generated file; the `use` lines
// above remain for the hand-written `MoveEffect` enum below.
include!(concat!(env!("OUT_DIR"), "/moves_gen.rs"));

/// Number of real moves (excluding `MoveId::None`) — derived from the
/// generated enum so it grows automatically when the editor adds moves.
pub const NUM_MOVES: u8 = (MoveId::COUNT - 1) as u8;

pub fn move_id_from_u8(val: u8) -> MoveId {
    <MoveId as num_traits::FromPrimitive>::from_u8(val).unwrap_or(MoveId::Pound)
}

impl MoveId {
    pub fn from_id(id: u8) -> Self {
        num_traits::FromPrimitive::from_u8(id).unwrap_or(MoveId::None)
    }
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    Display,
    EnumCount,
    EnumIter,
    EnumString,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(u8)]
pub enum MoveEffect {
    NoAdditionalEffect = 0x00,
    Effect01 = 0x01,
    PoisonSideEffect1 = 0x02,
    DrainHpEffect = 0x03,
    BurnSideEffect1 = 0x04,
    FreezeSideEffect1 = 0x05,
    ParalyzeSideEffect1 = 0x06,
    ExplodeEffect = 0x07,
    DreamEaterEffect = 0x08,
    MirrorMoveEffect = 0x09,
    AttackUp1Effect = 0x0A,
    DefenseUp1Effect = 0x0B,
    SpeedUp1Effect = 0x0C,
    SpecialUp1Effect = 0x0D,
    AccuracyUp1Effect = 0x0E,
    EvasionUp1Effect = 0x0F,
    PayDayEffect = 0x10,
    SwiftEffect = 0x11,
    AttackDown1Effect = 0x12,
    DefenseDown1Effect = 0x13,
    SpeedDown1Effect = 0x14,
    SpecialDown1Effect = 0x15,
    AccuracyDown1Effect = 0x16,
    EvasionDown1Effect = 0x17,
    ConversionEffect = 0x18,
    HazeEffect = 0x19,
    BideEffect = 0x1A,
    ThrashPetalDanceEffect = 0x1B,
    SwitchAndTeleportEffect = 0x1C,
    TwoToFiveAttacksEffect = 0x1D,
    Effect1E = 0x1E,
    FlinchSideEffect1 = 0x1F,
    SleepEffect = 0x20,
    PoisonSideEffect2 = 0x21,
    BurnSideEffect2 = 0x22,
    FreezeSideEffect2 = 0x23,
    ParalyzeSideEffect2 = 0x24,
    FlinchSideEffect2 = 0x25,
    OhkoEffect = 0x26,
    ChargeEffect = 0x27,
    SuperFangEffect = 0x28,
    SpecialDamageEffect = 0x29,
    TrappingEffect = 0x2A,
    FlyEffect = 0x2B,
    AttackTwiceEffect = 0x2C,
    JumpKickEffect = 0x2D,
    MistEffect = 0x2E,
    FocusEnergyEffect = 0x2F,
    RecoilEffect = 0x30,
    ConfusionEffect = 0x31,
    AttackUp2Effect = 0x32,
    DefenseUp2Effect = 0x33,
    SpeedUp2Effect = 0x34,
    SpecialUp2Effect = 0x35,
    AccuracyUp2Effect = 0x36,
    EvasionUp2Effect = 0x37,
    HealEffect = 0x38,
    TransformEffect = 0x39,
    AttackDown2Effect = 0x3A,
    DefenseDown2Effect = 0x3B,
    SpeedDown2Effect = 0x3C,
    SpecialDown2Effect = 0x3D,
    AccuracyDown2Effect = 0x3E,
    EvasionDown2Effect = 0x3F,
    LightScreenEffect = 0x40,
    ReflectEffect = 0x41,
    PoisonEffect = 0x42,
    ParalyzeEffect = 0x43,
    AttackDownSideEffect = 0x44,
    DefenseDownSideEffect = 0x45,
    SpeedDownSideEffect = 0x46,
    SpecialDownSideEffect = 0x47,
    ConfusionSideEffect = 0x4C,
    TwineedleEffect = 0x4D,
    SubstituteEffect = 0x4F,
    HyperBeamEffect = 0x50,
    RageEffect = 0x51,
    MimicEffect = 0x52,
    MetronomeEffect = 0x53,
    LeechSeedEffect = 0x54,
    SplashEffect = 0x55,
    DisableEffect = 0x56,
}
