use num_derive::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use strum_macros::{Display, EnumCount, EnumIter, EnumString};

pub use jrpg_engine::items::ItemKind;

// The `ItemId` enum is generated by `pokered-data/build.rs` from
// `data/items/item_list.json` (see `generate_item_enum`): `NoItem = 0x00`, the
// canonical list order keeps its byte IDs (0x01..=0x53), items added through
// the editor are appended after the base list, and Hm01-05 / Tm01-50 keep
// their fixed 0xC4..=0xFA ids. The derive set is emitted fully-qualified into
// the generated file; the `use` lines above remain for the hand-written
// enums below (`CustomKind`, `HmId`, `TmId`, `ItemEffect`, `ShopId`).
include!(concat!(env!("OUT_DIR"), "/items_gen.rs"));

pub const NUM_ITEMS: u8 = 0x53;
/// Highest GB item id (TM50 = $FA); TM/HM ids live above NUM_ITEMS.
pub const MAX_ITEM_ID: u8 = 0xFA;

impl ItemId {
    pub fn from_id(id: u8) -> Self {
        num_traits::FromPrimitive::from_u8(id).unwrap_or(ItemId::NoItem)
    }

    /// SCREAMING_SNAKE constant name matching the original asm item constants
    /// (e.g. `ItemId::OaksParcel` -> "OAKS_PARCEL", `PokeBall` -> "POKE_BALL",
    /// `SilphScope` -> "SILPH_SCOPE", `LiftKey` -> "LIFT_KEY").
    ///
    /// Derived from the PascalCase variant name (via `Debug`): a `_` is inserted
    /// before each interior uppercase letter or digit-run boundary, then the whole
    /// string is upper-cased. Best-effort for vitamin/TM-style names; key items —
    /// which is what scripts gate on — round-trip exactly.
    pub fn const_name(&self) -> String {
        let variant = format!("{:?}", self);
        let chars: Vec<char> = variant.chars().collect();
        let mut out = String::with_capacity(chars.len() + 4);
        for (i, &c) in chars.iter().enumerate() {
            if i > 0 {
                let prev = chars[i - 1];
                // Insert a separator at a "case/kind boundary":
                //   lower|digit -> Upper   (Poke|Ball, X|Accuracy)
                //   Upper       -> digit   (Unused|2C, Tm|01-style)
                let boundary = (c.is_ascii_uppercase() && !prev.is_ascii_uppercase())
                    || (c.is_ascii_digit() && prev.is_ascii_alphabetic());
                if boundary {
                    out.push('_');
                }
            }
            out.push(c.to_ascii_uppercase());
        }
        out
    }

    /// Inverse of [`const_name`](Self::const_name): find the item whose
    /// `const_name()` equals `name`. Returns `None` for unknown names or `NoItem`.
    ///
    /// Matching is underscore-insensitive, so both `"TM_34"` (the canonical
    /// `const_name`) and `"TM34"` resolve to `ItemId::Tm34` (likewise `HM01`,
    /// `X_ACCURACY`/`XACCURACY`). Scripts authored from the asm constants use the
    /// underscore-free `TM`/`HM` spelling, so accept it.
    pub fn from_const_name(name: &str) -> Option<Self> {
        let want: String = name.chars().filter(|c| *c != '_').collect();
        (0u8..=MAX_ITEM_ID).map(Self::from_id).find(|i| {
            *i != ItemId::NoItem
                && i.const_name().chars().filter(|c| *c != '_').collect::<String>() == want
        })
    }

    pub fn is_badge(self) -> bool {
        let v = self as u8;
        v >= 0x15 && v <= 0x1C
    }

    pub fn is_key_item(self) -> bool {
        matches!(
            self,
            ItemId::TownMap
                | ItemId::Bicycle
                | ItemId::Surfboard
                | ItemId::Pokedex
                | ItemId::OldAmber
                | ItemId::SecretKey
                | ItemId::BikeVoucher
                | ItemId::CardKey
                | ItemId::SsTicket
                | ItemId::GoldTeeth
                | ItemId::CoinCase
                | ItemId::OaksParcel
                | ItemId::Itemfinder
                | ItemId::SilphScope
                | ItemId::PokeFlute
                | ItemId::LiftKey
                | ItemId::OldRod
                | ItemId::GoodRod
                | ItemId::SuperRod
                | ItemId::DomeFossil
                | ItemId::HelixFossil
        )
    }
}

// ── CustomKind — game-specific item category extensions ───────────────────

/// Game-specific item kind extensions for Pokémon Red/Blue.
///
/// These categories are NOT universal to all JRPGs, so they live here
/// rather than in the engine's [`ItemKind`] enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CustomKind {
    /// Capture devices (Poké Balls, Great Balls, etc.)
    Ball,
    /// Technical Machines — one-time-use move teachers
    Tm,
    /// Hidden Machines — reusable move teachers
    Hm,
}

// Gen 1 has no equipment system, so pokered does not implement the engine's
// optional `EquipProvider` trait. A Gen 2+ port would implement it to model
// the Held Item slot.

// ── item_kind ──────────────────────────────────────────────────────────────

/// Classify an item into its generic category.
///
/// Returns the engine-standard [`ItemKind`] for each Gen 1 item.
/// Items unique to Pokémon (balls, TMs, key items) use [`Custom`](ItemKind::Custom).
pub fn item_kind(id: ItemId) -> ItemKind<CustomKind> {
    use ItemId::*;
    match id {
        // Recovery items
        Potion | SuperPotion | HyperPotion | MaxPotion
        | FreshWater | SodaPop | Lemonade
        | Antidote | BurnHeal | IceHeal | Awakening | ParlyzHeal
        | FullHeal | FullRestore => ItemKind::Consumable,

        // Revives
        Revive | MaxRevive => ItemKind::Consumable,

        // Vitamins
        HpUp | Protein | Iron | Carbos | Calcium => ItemKind::StatBoost,
        RareCandy => ItemKind::StatBoost,

        // Evolution stones
        MoonStone | FireStone | ThunderStone | WaterStone | LeafStone => ItemKind::Evolution,

        // PP restoration
        Ether | MaxEther | Elixer | MaxElixer | PpUp => ItemKind::Consumable,

        // Battle items
        XAccuracy | XAttack | XDefend | XSpeed | XSpecial
        | DireHit | GuardSpec => ItemKind::Consumable,
        PokeDoll => ItemKind::Consumable,

        // Repel
        Repel | SuperRepel | MaxRepel => ItemKind::Consumable,

        // Escape
        EscapeRope => ItemKind::Consumable,

        // Capture devices (Pokémon-specific → Custom)
        MasterBall | UltraBall | GreatBall | PokeBall | SafariBall => {
            ItemKind::Custom(CustomKind::Ball)
        }

        // Key items
        Bicycle | TownMap | Surfboard | Pokedex
        | OldAmber | SecretKey | BikeVoucher | CardKey
        | SsTicket | GoldTeeth | CoinCase | OaksParcel
        | Itemfinder | SilphScope | PokeFlute | LiftKey
        | OldRod | GoodRod | SuperRod
        | DomeFossil | HelixFossil => ItemKind::KeyItem,

        // Currency items
        Nugget => ItemKind::Currency,

        // Technical / Hidden Machines — move-teaching items, storable in the bag.
        Hm01 | Hm02 | Hm03 | Hm04 | Hm05 => ItemKind::Custom(CustomKind::Hm),
        id if (id as u8) >= 0xC9 && (id as u8) <= 0xFA => ItemKind::Custom(CustomKind::Tm),

        // Badges, unused items, and anything else → KeyItem by default
        _ => ItemKind::KeyItem,
    }
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, FromPrimitive, ToPrimitive,
)]
#[repr(u8)]
pub enum HmId {
    Hm01Cut = 1,
    Hm02Fly = 2,
    Hm03Surf = 3,
    Hm04Strength = 4,
    Hm05Flash = 5,
}

pub const NUM_HMS: u8 = 5;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, FromPrimitive, ToPrimitive,
)]
#[repr(u8)]
pub enum TmId {
    Tm01 = 1,
    Tm02 = 2,
    Tm03 = 3,
    Tm04 = 4,
    Tm05 = 5,
    Tm06 = 6,
    Tm07 = 7,
    Tm08 = 8,
    Tm09 = 9,
    Tm10 = 10,
    Tm11 = 11,
    Tm12 = 12,
    Tm13 = 13,
    Tm14 = 14,
    Tm15 = 15,
    Tm16 = 16,
    Tm17 = 17,
    Tm18 = 18,
    Tm19 = 19,
    Tm20 = 20,
    Tm21 = 21,
    Tm22 = 22,
    Tm23 = 23,
    Tm24 = 24,
    Tm25 = 25,
    Tm26 = 26,
    Tm27 = 27,
    Tm28 = 28,
    Tm29 = 29,
    Tm30 = 30,
    Tm31 = 31,
    Tm32 = 32,
    Tm33 = 33,
    Tm34 = 34,
    Tm35 = 35,
    Tm36 = 36,
    Tm37 = 37,
    Tm38 = 38,
    Tm39 = 39,
    Tm40 = 40,
    Tm41 = 41,
    Tm42 = 42,
    Tm43 = 43,
    Tm44 = 44,
    Tm45 = 45,
    Tm46 = 46,
    Tm47 = 47,
    Tm48 = 48,
    Tm49 = 49,
    Tm50 = 50,
}

pub const NUM_TMS: u8 = 50;

use crate::moves::MoveId;

pub const TM_MOVES: [MoveId; 50] = [
    MoveId::MegaPunch,
    MoveId::RazorWind,
    MoveId::SwordsDance,
    MoveId::Whirlwind,
    MoveId::MegaKick,
    MoveId::Toxic,
    MoveId::HornDrill,
    MoveId::BodySlam,
    MoveId::TakeDown,
    MoveId::DoubleEdge,
    MoveId::Bubblebeam,
    MoveId::WaterGun,
    MoveId::IceBeam,
    MoveId::Blizzard,
    MoveId::HyperBeam,
    MoveId::PayDay,
    MoveId::Submission,
    MoveId::Counter,
    MoveId::SeismicToss,
    MoveId::Rage,
    MoveId::MegaDrain,
    MoveId::Solarbeam,
    MoveId::DragonRage,
    MoveId::Thunderbolt,
    MoveId::Thunder,
    MoveId::Earthquake,
    MoveId::Fissure,
    MoveId::Dig,
    MoveId::PsychicM,
    MoveId::Teleport,
    MoveId::Mimic,
    MoveId::DoubleTeam,
    MoveId::Reflect,
    MoveId::Bide,
    MoveId::Metronome,
    MoveId::Selfdestruct,
    MoveId::EggBomb,
    MoveId::FireBlast,
    MoveId::Swift,
    MoveId::SkullBash,
    MoveId::Softboiled,
    MoveId::DreamEater,
    MoveId::SkyAttack,
    MoveId::Rest,
    MoveId::ThunderWave,
    MoveId::Psywave,
    MoveId::Explosion,
    MoveId::RockSlide,
    MoveId::TriAttack,
    MoveId::Substitute,
];

pub const HM_MOVES: [MoveId; 5] = [
    MoveId::Cut,
    MoveId::Fly,
    MoveId::Surf,
    MoveId::Strength,
    MoveId::Flash,
];

// ── ItemEffect — describes what an item does ───────────────────────────

/// Describes the combat / field effect of an item.
///
/// This enum bridges the gap between the abstract [`jrpg_engine::items::ItemProvider`]
/// trait and the concrete Pokémon Red/Blue item effects.  The actual application
/// of effects to a [`Pokemon`] lives in `pokered-core::items` because the data
/// crate cannot reference types from `pokered-core`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ItemEffect {
    /// Heal a fixed amount of HP (Potion = 20, Super Potion = 50, etc.).
    Heal(u32),
    /// Heal HP to full (Max Potion).
    FullHeal,
    /// Heal HP to full and cure all status (Full Restore).
    FullRestore,
    /// Revive a fainted Pokémon. `true` = full HP (Max Revive), `false` = half HP.
    Revive(bool),
    /// Cure a specific status condition.
    CurePoison,
    CureBurn,
    CureFreeze,
    CureSleep,
    CureParalysis,
    /// Cure any status condition (Full Heal).
    CureAllStatus,
    /// Permanently boost a stat via vitamin. Value is stat index: 0=HP, 1=Atk, etc.
    Vitamin(u8),
    /// Level up by one (Rare Candy).
    RareCandy,
    /// Boost a battle stat stage. Value is stat index.
    BattleStat(u8),
    /// Set a battle status2 flag (X Accuracy, Guard Spec., Dire Hit). Value is flag ID.
    BattleFlag(u8),
    /// Escape from wild battle (Poké Doll).
    Escape,
    /// Restore PP to a single move. `true` = full restore (Max Ether).
    PpRestoreSingle(bool),
    /// Restore PP to all moves. `true` = full restore (Max Elixir).
    PpRestoreAll(bool),
    /// Apply a PP Up to one move.
    PpUp,
    /// Evolution stone. Value: 0=Moon, 1=Fire, 2=Thunder, 3=Water, 4=Leaf.
    EvolutionStone(u8),
    /// No combat/field effect — key item, badge, etc.
    None,
}

// ── ShopId — mart location identifiers ────────────────────────────────

/// Identifies a shop / Poké Mart location in the game world.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ShopId {
    ViridianMart,
    PewterMart,
    CeruleanMart,
    VermilionMart,
    LavenderMart,
    CeladonMart2F,
    CeladonMart4F,
    CeladonMart5F,
    FuchsiaMart,
    CinnabarMart,
    SaffronMart,
    IndigoPlateauMart,
}

#[cfg(test)]
mod item_kind_tests {
    use super::*;

    #[test]
    fn potion_is_consumable() {
        assert_eq!(item_kind(ItemId::Potion), ItemKind::Consumable);
    }

    #[test]
    fn master_ball_is_custom() {
        assert_eq!(
            item_kind(ItemId::MasterBall),
            ItemKind::Custom(CustomKind::Ball)
        );
    }

    #[test]
    fn bicycle_is_key_item() {
        assert_eq!(item_kind(ItemId::Bicycle), ItemKind::KeyItem);
    }

    #[test]
    fn rare_candy_is_stat_boost() {
        assert_eq!(item_kind(ItemId::RareCandy), ItemKind::StatBoost);
    }

    #[test]
    fn moon_stone_is_evolution() {
        assert_eq!(item_kind(ItemId::MoonStone), ItemKind::Evolution);
    }

    #[test]
    fn nugget_is_currency() {
        assert_eq!(item_kind(ItemId::Nugget), ItemKind::Currency);
    }

    #[test]
    fn full_restore_is_consumable() {
        assert_eq!(item_kind(ItemId::FullRestore), ItemKind::Consumable);
    }

    #[test]
    fn escape_rope_is_consumable() {
        assert_eq!(item_kind(ItemId::EscapeRope), ItemKind::Consumable);
    }

    #[test]
    fn protein_is_stat_boost() {
        assert_eq!(item_kind(ItemId::Protein), ItemKind::StatBoost);
    }

    #[test]
    fn great_ball_is_custom_ball() {
        assert_eq!(
            item_kind(ItemId::GreatBall),
            ItemKind::Custom(CustomKind::Ball)
        );
    }

    #[test]
    fn badge_is_key_item() {
        assert_eq!(item_kind(ItemId::BoulderBadge), ItemKind::KeyItem);
    }

    #[test]
    fn coin_case_is_key_item() {
        assert_eq!(item_kind(ItemId::CoinCase), ItemKind::KeyItem);
    }

    #[test]
    fn elixer_is_consumable() {
        assert_eq!(item_kind(ItemId::Elixer), ItemKind::Consumable);
    }

    #[test]
    fn guard_spec_is_consumable() {
        assert_eq!(item_kind(ItemId::GuardSpec), ItemKind::Consumable);
    }
}

#[cfg(test)]
mod const_name_tests {
    use super::item_kind;
    use super::ItemId;
    use crate::items::CustomKind;
    use jrpg_engine::items::ItemKind;

    #[test]
    fn const_name_key_items() {
        assert_eq!(ItemId::OaksParcel.const_name(), "OAKS_PARCEL");
        assert_eq!(ItemId::PokeBall.const_name(), "POKE_BALL");
        assert_eq!(ItemId::SilphScope.const_name(), "SILPH_SCOPE");
        assert_eq!(ItemId::LiftKey.const_name(), "LIFT_KEY");
        assert_eq!(ItemId::TownMap.const_name(), "TOWN_MAP");
    }

    #[test]
    fn from_const_name_round_trips() {
        for item in [
            ItemId::OaksParcel,
            ItemId::PokeBall,
            ItemId::SilphScope,
            ItemId::LiftKey,
            ItemId::TownMap,
            ItemId::CardKey,
            ItemId::SsTicket,
            ItemId::Nugget,
        ] {
            assert_eq!(
                ItemId::from_const_name(&item.const_name()),
                Some(item),
                "round-trip failed for {:?}",
                item,
            );
        }
    }

    #[test]
    fn from_const_name_unknown_is_none() {
        assert_eq!(ItemId::from_const_name("NOT_A_REAL_ITEM"), None);
        // NoItem must never be resolvable by name.
        assert_eq!(ItemId::from_const_name("NO_ITEM"), None);
    }

    #[test]
    fn from_const_name_is_underscore_insensitive() {
        // Scripts authored from asm constants may drop the case-boundary '_';
        // both spellings must resolve to the same item.
        assert_eq!(ItemId::HpUp.const_name(), "HP_UP");
        assert_eq!(ItemId::from_const_name("HPUP"), Some(ItemId::HpUp));
        assert_eq!(ItemId::from_const_name("HP_UP"), Some(ItemId::HpUp));
    }

    /// TMs/HMs resolve to the bag-storable ItemId variants (ids $C4-$FA).
    #[test]
    fn tms_and_hms_resolve_from_const_name() {
        assert_eq!(ItemId::from_const_name("TM34"), Some(ItemId::Tm34));
        assert_eq!(ItemId::from_const_name("TM_13"), Some(ItemId::Tm13));
        assert_eq!(ItemId::from_const_name("TM01"), Some(ItemId::Tm01));
        assert_eq!(ItemId::from_const_name("TM50"), Some(ItemId::Tm50));
        assert_eq!(ItemId::from_const_name("HM03"), Some(ItemId::Hm03));
        // Round-trip const_name.
        assert_eq!(ItemId::Tm34.const_name(), "TM_34");
        assert_eq!(ItemId::from_const_name(&ItemId::Tm34.const_name()), Some(ItemId::Tm34));
        // Item ids match the original GB table (TM01 = $C9, HM01 = $C4).
        assert_eq!(ItemId::Tm01 as u8, 0xC9);
        assert_eq!(ItemId::Tm50 as u8, 0xFA);
        assert_eq!(ItemId::Hm01 as u8, 0xC4);
    }

    /// TMs are categorized as Custom(Tm) so they are not treated as key items.
    #[test]
    fn tm_item_kind_is_custom() {
        assert!(matches!(
            item_kind(ItemId::Tm27),
            ItemKind::Custom(CustomKind::Tm)
        ));
        assert!(matches!(
            item_kind(ItemId::Hm03),
            ItemKind::Custom(CustomKind::Hm)
        ));
    }
}
