use crate::alloc_prelude::*;
use num_derive::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use strum::EnumCount;
use strum_macros::{Display, EnumIter, EnumString};

// The `Species` enum is generated by `pokered-data/build.rs` from the
// `pokemon/*.json` filenames (see `generate_species_enum`): `None = 0`, the
// canonical dex order keeps IDs 1..=151, and species added through the
// editor are appended with IDs 152+ (sorted by filename). The derive set is
// emitted fully-qualified into the generated file; the `use` lines above
// remain for the hand-written `GrowthRate` enum below.
include!(concat!(env!("OUT_DIR"), "/species_gen.rs"));

/// Number of real species (excluding `Species::None`) — derived from the
/// generated enum so it grows automatically when the editor adds species.
pub const NUM_POKEMON: u8 = (Species::COUNT - 1) as u8;

impl Species {
    pub fn is_valid(self) -> bool {
        let v = self as u8;
        v >= 1 && v <= NUM_POKEMON
    }

    pub fn from_index_id(id: u8) -> Self {
        num_traits::FromPrimitive::from_u8(id).unwrap_or(Species::None)
    }

    /// Original Game Boy species byte (not the Pokédex number). Used only
    /// at the SRAM boundary; game/editor data keep their stable dex IDs.
    pub fn to_rom_id(self) -> u8 {
        match self {
            Self::Rhydon => 0x01,
            Self::Kangaskhan => 0x02,
            Self::NidoranM => 0x03,
            Self::Clefairy => 0x04,
            Self::Spearow => 0x05,
            Self::Voltorb => 0x06,
            Self::Nidoking => 0x07,
            Self::Slowbro => 0x08,
            Self::Ivysaur => 0x09,
            Self::Exeggutor => 0x0A,
            Self::Lickitung => 0x0B,
            Self::Exeggcute => 0x0C,
            Self::Grimer => 0x0D,
            Self::Gengar => 0x0E,
            Self::NidoranF => 0x0F,
            Self::Nidoqueen => 0x10,
            Self::Cubone => 0x11,
            Self::Rhyhorn => 0x12,
            Self::Lapras => 0x13,
            Self::Arcanine => 0x14,
            Self::Mew => 0x15,
            Self::Gyarados => 0x16,
            Self::Shellder => 0x17,
            Self::Tentacool => 0x18,
            Self::Gastly => 0x19,
            Self::Scyther => 0x1A,
            Self::Staryu => 0x1B,
            Self::Blastoise => 0x1C,
            Self::Pinsir => 0x1D,
            Self::Tangela => 0x1E,
            Self::Growlithe => 0x21,
            Self::Onix => 0x22,
            Self::Fearow => 0x23,
            Self::Pidgey => 0x24,
            Self::Slowpoke => 0x25,
            Self::Kadabra => 0x26,
            Self::Graveler => 0x27,
            Self::Chansey => 0x28,
            Self::Machoke => 0x29,
            Self::MrMime => 0x2A,
            Self::Hitmonlee => 0x2B,
            Self::Hitmonchan => 0x2C,
            Self::Arbok => 0x2D,
            Self::Parasect => 0x2E,
            Self::Psyduck => 0x2F,
            Self::Drowzee => 0x30,
            Self::Golem => 0x31,
            Self::Magmar => 0x33,
            Self::Electabuzz => 0x35,
            Self::Magneton => 0x36,
            Self::Koffing => 0x37,
            Self::Mankey => 0x39,
            Self::Seel => 0x3A,
            Self::Diglett => 0x3B,
            Self::Tauros => 0x3C,
            Self::Farfetchd => 0x40,
            Self::Venonat => 0x41,
            Self::Dragonite => 0x42,
            Self::Doduo => 0x46,
            Self::Poliwag => 0x47,
            Self::Jynx => 0x48,
            Self::Moltres => 0x49,
            Self::Articuno => 0x4A,
            Self::Zapdos => 0x4B,
            Self::Ditto => 0x4C,
            Self::Meowth => 0x4D,
            Self::Krabby => 0x4E,
            Self::Vulpix => 0x52,
            Self::Ninetales => 0x53,
            Self::Pikachu => 0x54,
            Self::Raichu => 0x55,
            Self::Dratini => 0x58,
            Self::Dragonair => 0x59,
            Self::Kabuto => 0x5A,
            Self::Kabutops => 0x5B,
            Self::Horsea => 0x5C,
            Self::Seadra => 0x5D,
            Self::Sandshrew => 0x60,
            Self::Sandslash => 0x61,
            Self::Omanyte => 0x62,
            Self::Omastar => 0x63,
            Self::Jigglypuff => 0x64,
            Self::Wigglytuff => 0x65,
            Self::Eevee => 0x66,
            Self::Flareon => 0x67,
            Self::Jolteon => 0x68,
            Self::Vaporeon => 0x69,
            Self::Machop => 0x6A,
            Self::Zubat => 0x6B,
            Self::Ekans => 0x6C,
            Self::Paras => 0x6D,
            Self::Poliwhirl => 0x6E,
            Self::Poliwrath => 0x6F,
            Self::Weedle => 0x70,
            Self::Kakuna => 0x71,
            Self::Beedrill => 0x72,
            Self::Dodrio => 0x74,
            Self::Primeape => 0x75,
            Self::Dugtrio => 0x76,
            Self::Venomoth => 0x77,
            Self::Dewgong => 0x78,
            Self::Caterpie => 0x7B,
            Self::Metapod => 0x7C,
            Self::Butterfree => 0x7D,
            Self::Machamp => 0x7E,
            Self::Golduck => 0x80,
            Self::Hypno => 0x81,
            Self::Golbat => 0x82,
            Self::Mewtwo => 0x83,
            Self::Snorlax => 0x84,
            Self::Magikarp => 0x85,
            Self::Muk => 0x88,
            Self::Kingler => 0x8A,
            Self::Cloyster => 0x8B,
            Self::Electrode => 0x8D,
            Self::Clefable => 0x8E,
            Self::Weezing => 0x8F,
            Self::Persian => 0x90,
            Self::Marowak => 0x91,
            Self::Haunter => 0x93,
            Self::Abra => 0x94,
            Self::Alakazam => 0x95,
            Self::Pidgeotto => 0x96,
            Self::Pidgeot => 0x97,
            Self::Starmie => 0x98,
            Self::Bulbasaur => 0x99,
            Self::Venusaur => 0x9A,
            Self::Tentacruel => 0x9B,
            Self::Goldeen => 0x9D,
            Self::Seaking => 0x9E,
            Self::Ponyta => 0xA3,
            Self::Rapidash => 0xA4,
            Self::Rattata => 0xA5,
            Self::Raticate => 0xA6,
            Self::Nidorino => 0xA7,
            Self::Nidorina => 0xA8,
            Self::Geodude => 0xA9,
            Self::Porygon => 0xAA,
            Self::Aerodactyl => 0xAB,
            Self::Magnemite => 0xAD,
            Self::Charmander => 0xB0,
            Self::Squirtle => 0xB1,
            Self::Charmeleon => 0xB2,
            Self::Wartortle => 0xB3,
            Self::Charizard => 0xB4,
            Self::Oddish => 0xB9,
            Self::Gloom => 0xBA,
            Self::Vileplume => 0xBB,
            Self::Bellsprout => 0xBC,
            Self::Weepinbell => 0xBD,
            Self::Victreebel => 0xBE,
            _ => 0,
        }
    }

    pub fn from_rom_id(id: u8) -> Self {
        match id {
            0x01 => Self::Rhydon,
            0x02 => Self::Kangaskhan,
            0x03 => Self::NidoranM,
            0x04 => Self::Clefairy,
            0x05 => Self::Spearow,
            0x06 => Self::Voltorb,
            0x07 => Self::Nidoking,
            0x08 => Self::Slowbro,
            0x09 => Self::Ivysaur,
            0x0A => Self::Exeggutor,
            0x0B => Self::Lickitung,
            0x0C => Self::Exeggcute,
            0x0D => Self::Grimer,
            0x0E => Self::Gengar,
            0x0F => Self::NidoranF,
            0x10 => Self::Nidoqueen,
            0x11 => Self::Cubone,
            0x12 => Self::Rhyhorn,
            0x13 => Self::Lapras,
            0x14 => Self::Arcanine,
            0x15 => Self::Mew,
            0x16 => Self::Gyarados,
            0x17 => Self::Shellder,
            0x18 => Self::Tentacool,
            0x19 => Self::Gastly,
            0x1A => Self::Scyther,
            0x1B => Self::Staryu,
            0x1C => Self::Blastoise,
            0x1D => Self::Pinsir,
            0x1E => Self::Tangela,
            0x21 => Self::Growlithe,
            0x22 => Self::Onix,
            0x23 => Self::Fearow,
            0x24 => Self::Pidgey,
            0x25 => Self::Slowpoke,
            0x26 => Self::Kadabra,
            0x27 => Self::Graveler,
            0x28 => Self::Chansey,
            0x29 => Self::Machoke,
            0x2A => Self::MrMime,
            0x2B => Self::Hitmonlee,
            0x2C => Self::Hitmonchan,
            0x2D => Self::Arbok,
            0x2E => Self::Parasect,
            0x2F => Self::Psyduck,
            0x30 => Self::Drowzee,
            0x31 => Self::Golem,
            0x33 => Self::Magmar,
            0x35 => Self::Electabuzz,
            0x36 => Self::Magneton,
            0x37 => Self::Koffing,
            0x39 => Self::Mankey,
            0x3A => Self::Seel,
            0x3B => Self::Diglett,
            0x3C => Self::Tauros,
            0x40 => Self::Farfetchd,
            0x41 => Self::Venonat,
            0x42 => Self::Dragonite,
            0x46 => Self::Doduo,
            0x47 => Self::Poliwag,
            0x48 => Self::Jynx,
            0x49 => Self::Moltres,
            0x4A => Self::Articuno,
            0x4B => Self::Zapdos,
            0x4C => Self::Ditto,
            0x4D => Self::Meowth,
            0x4E => Self::Krabby,
            0x52 => Self::Vulpix,
            0x53 => Self::Ninetales,
            0x54 => Self::Pikachu,
            0x55 => Self::Raichu,
            0x58 => Self::Dratini,
            0x59 => Self::Dragonair,
            0x5A => Self::Kabuto,
            0x5B => Self::Kabutops,
            0x5C => Self::Horsea,
            0x5D => Self::Seadra,
            0x60 => Self::Sandshrew,
            0x61 => Self::Sandslash,
            0x62 => Self::Omanyte,
            0x63 => Self::Omastar,
            0x64 => Self::Jigglypuff,
            0x65 => Self::Wigglytuff,
            0x66 => Self::Eevee,
            0x67 => Self::Flareon,
            0x68 => Self::Jolteon,
            0x69 => Self::Vaporeon,
            0x6A => Self::Machop,
            0x6B => Self::Zubat,
            0x6C => Self::Ekans,
            0x6D => Self::Paras,
            0x6E => Self::Poliwhirl,
            0x6F => Self::Poliwrath,
            0x70 => Self::Weedle,
            0x71 => Self::Kakuna,
            0x72 => Self::Beedrill,
            0x74 => Self::Dodrio,
            0x75 => Self::Primeape,
            0x76 => Self::Dugtrio,
            0x77 => Self::Venomoth,
            0x78 => Self::Dewgong,
            0x7B => Self::Caterpie,
            0x7C => Self::Metapod,
            0x7D => Self::Butterfree,
            0x7E => Self::Machamp,
            0x80 => Self::Golduck,
            0x81 => Self::Hypno,
            0x82 => Self::Golbat,
            0x83 => Self::Mewtwo,
            0x84 => Self::Snorlax,
            0x85 => Self::Magikarp,
            0x88 => Self::Muk,
            0x8A => Self::Kingler,
            0x8B => Self::Cloyster,
            0x8D => Self::Electrode,
            0x8E => Self::Clefable,
            0x8F => Self::Weezing,
            0x90 => Self::Persian,
            0x91 => Self::Marowak,
            0x93 => Self::Haunter,
            0x94 => Self::Abra,
            0x95 => Self::Alakazam,
            0x96 => Self::Pidgeotto,
            0x97 => Self::Pidgeot,
            0x98 => Self::Starmie,
            0x99 => Self::Bulbasaur,
            0x9A => Self::Venusaur,
            0x9B => Self::Tentacruel,
            0x9D => Self::Goldeen,
            0x9E => Self::Seaking,
            0xA3 => Self::Ponyta,
            0xA4 => Self::Rapidash,
            0xA5 => Self::Rattata,
            0xA6 => Self::Raticate,
            0xA7 => Self::Nidorino,
            0xA8 => Self::Nidorina,
            0xA9 => Self::Geodude,
            0xAA => Self::Porygon,
            0xAB => Self::Aerodactyl,
            0xAD => Self::Magnemite,
            0xB0 => Self::Charmander,
            0xB1 => Self::Squirtle,
            0xB2 => Self::Charmeleon,
            0xB3 => Self::Wartortle,
            0xB4 => Self::Charizard,
            0xB9 => Self::Oddish,
            0xBA => Self::Gloom,
            0xBB => Self::Vileplume,
            0xBC => Self::Bellsprout,
            0xBD => Self::Weepinbell,
            0xBE => Self::Victreebel,
            _ => Self::None,
        }
    }

    /// The enum's PascalCase name as `format!("{:?}", self)` produces it
    /// ("MrMime", "NidoranF", "Poliwhirl"). Used to match a scene/DSL token.
    pub fn pascal_name(self) -> String {
        format!("{:?}", self)
    }

    /// Parse a scene/DSL species token — SCREAMING_SNAKE like "MR_MIME",
    /// "NIDORAN_F", "POLIWHIRL" — into a Species. Converts each `_`-separated
    /// word to Capitalized form so it matches the strum `EnumString` variant
    /// names (which are PascalCase, e.g. `MrMime`, `NidoranF`). PascalCase
    /// tokens (e.g. from `{:?}` formatting) are accepted as-is.
    pub fn from_scene_name(token: &str) -> Option<Species> {
        use core::str::FromStr;
        Species::from_str(token)
            .ok()
            .or_else(|| Species::from_str(&scene_species_to_pascal(token)).ok())
    }
}

/// SCREAMING_SNAKE species token -> PascalCase variant name (string form).
/// "MR_MIME" -> "MrMime", "NIDORAN_F" -> "NidoranF", "POLIWHIRL" -> "Poliwhirl".
pub fn scene_species_to_pascal(token: &str) -> String {
    token
        .split('_')
        .map(|w| {
            let mut cs = w.chars();
            match cs.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string() + &cs.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    Display,
    EnumCount,
    EnumIter,
    EnumString,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(u8)]
pub enum GrowthRate {
    MediumFast = 0,
    SlightlyFast = 1,
    SlightlySlow = 2,
    MediumSlow = 3,
    Fast = 4,
    Slow = 5,
}

#[cfg(test)]
mod scene_name_tests {
    use super::{scene_species_to_pascal, Species};

    #[test]
    fn scene_species_to_pascal_handles_multiword_and_single() {
        assert_eq!(scene_species_to_pascal("MR_MIME"), "MrMime");
        assert_eq!(scene_species_to_pascal("NIDORAN_F"), "NidoranF");
        assert_eq!(scene_species_to_pascal("NIDORAN_M"), "NidoranM");
        assert_eq!(scene_species_to_pascal("POLIWHIRL"), "Poliwhirl");
        assert_eq!(scene_species_to_pascal("FARFETCHD"), "Farfetchd");
    }

    #[test]
    fn from_scene_name_parses_trade_species() {
        assert_eq!(Species::from_scene_name("MR_MIME"), Some(Species::MrMime));
        assert_eq!(Species::from_scene_name("NIDORAN_F"), Some(Species::NidoranF));
        assert_eq!(Species::from_scene_name("NIDORAN_M"), Some(Species::NidoranM));
        assert_eq!(Species::from_scene_name("POLIWHIRL"), Some(Species::Poliwhirl));
        assert_eq!(Species::from_scene_name("JYNX"), Some(Species::Jynx));
        assert_eq!(Species::from_scene_name("FARFETCHD"), Some(Species::Farfetchd));
        assert_eq!(Species::from_scene_name("ELECTRODE"), Some(Species::Electrode));
        assert_eq!(Species::from_scene_name("NOTAPOKEMON"), None);
    }
}
