use num_derive::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use strum::EnumCount;
use strum_macros::{Display, EnumIter, EnumString};

// The `Species` enum is generated by `pokered-data/build.rs` from the
// `pokemon/*.json` filenames (see `generate_species_enum`): `None = 0`, the
// canonical dex order keeps IDs 1..=151, and species added through the
// editor are appended with IDs 152+ (sorted by filename). The derive set is
// emitted fully-qualified into the generated file; the `use` lines above
// remain for the hand-written `GrowthRate` enum below.
include!(concat!(env!("OUT_DIR"), "/species_gen.rs"));

/// Number of real species (excluding `Species::None`) — derived from the
/// generated enum so it grows automatically when the editor adds species.
pub const NUM_POKEMON: u8 = (Species::COUNT - 1) as u8;

impl Species {
    pub fn is_valid(self) -> bool {
        let v = self as u8;
        v >= 1 && v <= NUM_POKEMON
    }

    pub fn from_index_id(id: u8) -> Self {
        num_traits::FromPrimitive::from_u8(id).unwrap_or(Species::None)
    }

    /// The enum's PascalCase name as `format!("{:?}", self)` produces it
    /// ("MrMime", "NidoranF", "Poliwhirl"). Used to match a scene/DSL token.
    pub fn pascal_name(self) -> String {
        format!("{:?}", self)
    }

    /// Parse a scene/DSL species token — SCREAMING_SNAKE like "MR_MIME",
    /// "NIDORAN_F", "POLIWHIRL" — into a Species. Converts each `_`-separated
    /// word to Capitalized form so it matches the strum `EnumString` variant
    /// names (which are PascalCase, e.g. `MrMime`, `NidoranF`). PascalCase
    /// tokens (e.g. from `{:?}` formatting) are accepted as-is.
    pub fn from_scene_name(token: &str) -> Option<Species> {
        use std::str::FromStr;
        Species::from_str(token)
            .ok()
            .or_else(|| Species::from_str(&scene_species_to_pascal(token)).ok())
    }
}

/// SCREAMING_SNAKE species token -> PascalCase variant name (string form).
/// "MR_MIME" -> "MrMime", "NIDORAN_F" -> "NidoranF", "POLIWHIRL" -> "Poliwhirl".
pub fn scene_species_to_pascal(token: &str) -> String {
    token
        .split('_')
        .map(|w| {
            let mut cs = w.chars();
            match cs.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string() + &cs.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    Display,
    EnumCount,
    EnumIter,
    EnumString,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(u8)]
pub enum GrowthRate {
    MediumFast = 0,
    SlightlyFast = 1,
    SlightlySlow = 2,
    MediumSlow = 3,
    Fast = 4,
    Slow = 5,
}

#[cfg(test)]
mod scene_name_tests {
    use super::{scene_species_to_pascal, Species};

    #[test]
    fn scene_species_to_pascal_handles_multiword_and_single() {
        assert_eq!(scene_species_to_pascal("MR_MIME"), "MrMime");
        assert_eq!(scene_species_to_pascal("NIDORAN_F"), "NidoranF");
        assert_eq!(scene_species_to_pascal("NIDORAN_M"), "NidoranM");
        assert_eq!(scene_species_to_pascal("POLIWHIRL"), "Poliwhirl");
        assert_eq!(scene_species_to_pascal("FARFETCHD"), "Farfetchd");
    }

    #[test]
    fn from_scene_name_parses_trade_species() {
        assert_eq!(Species::from_scene_name("MR_MIME"), Some(Species::MrMime));
        assert_eq!(Species::from_scene_name("NIDORAN_F"), Some(Species::NidoranF));
        assert_eq!(Species::from_scene_name("NIDORAN_M"), Some(Species::NidoranM));
        assert_eq!(Species::from_scene_name("POLIWHIRL"), Some(Species::Poliwhirl));
        assert_eq!(Species::from_scene_name("JYNX"), Some(Species::Jynx));
        assert_eq!(Species::from_scene_name("FARFETCHD"), Some(Species::Farfetchd));
        assert_eq!(Species::from_scene_name("ELECTRODE"), Some(Species::Electrode));
        assert_eq!(Species::from_scene_name("NOTAPOKEMON"), None);
    }
}
