[package]
name = "pokered-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pokered-core = { path = "../pokered-core" }
pokered-data = { path = "../pokered-data" }
dotzuki-engine-dsl = { git = "https://github.com/liuyanghejerry/dotzuki", rev = "67d7f0a8310054dde053a0cf068430c8a585ab97" }
serde = { workspace = true }
serde_json = { workspace = true }
